category: Typography
subcategory: Loading & Displaying
description: "
Draws text to the screen. Displays the information specified in the first parameter on the screen in the position specified by the additional parameters. A default font will be used unless a font is set with the <b>textFont()</b> function and a default size will be used unless a font is set with <b>textSize()</b>. Change the color of the text with the <b>fill()</b> function. The text displays in relation to the <b>textAlign()</b> function, which gives the option to draw to the left, right, and center of the coordinates.<br/>
<br/>
The <b>x2</b> and <b>y2</b> parameters define a rectangular area to display within and may only be used with string data. When these parameters are specified, they are interpreted based on the current <b>rectMode()</b> setting. Text that does not fit completely within the rectangle specified will not be drawn to the screen.<br/>
<br/>
Note that Processing now lets you call <b>text()</b> without first specifying a PFont with <b>textFont()</b>. In that case, a generic sans-serif font will be used instead. (See the third example above.)
"
syntax: ""
related:
  - textAlign
  - textFont
  - textMode
  - textSize
  - rectMode
  - fill
  - string
