category: Shape
subcategory: Curves
description: "
Evaluates the curve at point <b>t</b> for points <b>a</b>, <b>b</b>, <b>c</b>, <b>d</b>. The parameter <b>t</b> may range from 0 (the start of the curve) and 1 (the end of the curve). <b>a</b> and <b>d</b> are points on the curve, and <b>b</b> and <b>c</b> are the control points. This can be used once with the <b>x</b> coordinates and a second time with the <b>y</b> coordinates to get the location of a curve at <b>t</b>.
"
syntax: "curvePoint(<c>a</c>, <c>b</c>, <c>c</c>, <c>d</c>, <c>t</c>)"
parameters:
  - label: 'a'
    description: "float: coordinate of first point on the curve"
  - label: 'b'
    description: "float: coordinate of second point on the curve"
  - label: 'c'
    description: "float: coordinate of third point on the curve"
  - label: 'd'
    description: "float: coordinate of fourth point on the curve"
  - label: 't'
    description: "float: value between 0 and 1"
related:
  - curve
  - curveVertex
  - bezierPoint
