category: Math
subcategory: Trigonometry
description: "
The inverse of <b>sin()</b>, returns the arc sine of a value. This function expects the values in the range of -1 to 1 and values are returned in the range <b>-PI/2</b> to <b>PI/2</b>.
"
syntax: "asin(<c>value</c>)"
parameters:
  - label: 'value'
    description: "float: the value whose arc sine is to be returned"
related:
  - sin
  - acos
  - atan
