category: Data
subcategory: String Methods
description: "
Return the lowest index in the string where a substring is found. Optional
arguments start and end specify a range to search in. If the substring is not
found, returns <b>-1</b>.

"
syntax: "a.find(<c>sub</c>)\na.find(<c>sub</c>,<c>start</c>,<c>end</c>)"
parameters:
  - label: 'sub'
    description: "substring to search for"
  - label: 'start'
    description: "starting point in search range"
  - label: 'end'
    description: "end point in search range"
related:
  - string
  - string_formatting
  - string_find
  - string_strip
  - string_join
  - string_replace
