category: Control
subcategory: Relational Operators
description: "
Determines if two values are equivalent. The equality operator is different from the assignment operator.<br /> 
"
syntax: "<c>value1</c> == <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int, float, byte, boolean"
  - label: 'value2'
    description: "int, float, byte, boolean"
related:
  - greaterthan
  - lessthan
  - greaterthanorequalto
  - lessthanorequalto
  - inequality
