category: XMLElement
subcategory: Method
description: "
Checks whether or not an element has the specified attribute.  The attribute must be specified as a String, and a Boolean is returned.
"
syntax: ".hasAttribute(name)\n"
