category: Lights, Camera
subcategory: Material Properties
description: "
Sets the amount of gloss in the surface of shapes. Used in combination with <b>ambient()</b>, <b>specular()</b>, and <b>emissive()</b> in setting the material properties of shapes.
"
syntax: "shininess(<c>shine</c>)"
parameters:
  - label: 'shine'
    description: "float: degree of shininess"
related:
  - emissive
  - ambient
  - specular
