category: Shape
subcategory: Loading & Displaying
description: "
Draws shapes to the display window. Shapes must be in the sketch's \"data\" directory to load correctly. Select \"Add file...\" from the \"Sketch\" menu to add the shape. Processing currently works with SVG, OBJ, and custom-created shapes. The <b>shape</b> parameter specifies the shape to display and the coordinate parameters define the location of the shape from its upper-left corner. The shape is displayed at its original size unless the <b>c</b> and <b>d</b> parameters specify a different size. The <b>shapeMode()</b> function can be used to change the way these parameters are interpreted.
"
syntax: "shape(<c>shape</c>)\nshape(<c>shape</c>, <c>x</c>, <c>y</c>)\nshape(<c>shape</c>, <c>a</c>, <c>b</c>, <c>c</c>, <c>d</c>)"
parameters:
  - label: 'shape'
    description: "PShape: the shape to display"
  - label: 'x'
    description: "float: x-coordinate of the shape"
  - label: 'y'
    description: "float: y-coordinate of the shape"
  - label: 'a'
    description: "float: x-coordinate of the shape"
  - label: 'b'
    description: "float: y-coordinate of the shape"
  - label: 'c'
    description: "float: width to display the shape"
  - label: 'd'
    description: "float: height to display the shape"
related:
  - PShape
  - loadShape
  - shapeMode
