category: TableRow
subcategory: Method
description: "
Retrieves an integer value from the <b>TableRow</b>'s specified column. The column may be specified by either its ID or title.
"
syntax: ".getInt(<c>column</c>)\n.getInt(<c>columnName</c>)"
parameters:
  - label: 'column'
    description: "int: ID number of the column to reference"
  - label: 'columnName'
    description: "String: title of the column to reference"
related:
  - XML_getFloat
  - XML_getString
