category: PVector
subcategory: Method
description: "
Calculates the magnitude (length) of the vector and returns the result as a float (this is simply the equation <em>sqrt(x*x + y*y + z*z)</em>.)
"
syntax: ".mag()"
related:
  - PVector_magSq
