category: Table
subcategory: Method
description: "
Retrieves a float value from the <b>Table</b>'s specified row and column. The row is specified by its ID, while the column may be specified by either its ID or title.
"
syntax: ".getFloat(<c>row</c>, <c>column</c>)\n.getFloat(<c>row</c>, <c>columnName</c>)"
parameters:
  - label: 'row'
    description: "int: ID number of the row to reference"
  - label: 'column'
    description: "int: ID number of the column to reference"
  - label: 'columnName'
    description: "String: title of the column to reference"
related:
  - XML_getInt
  - XML_getString
  - Table_getStringColumn
  - XML_setInt
  - XML_setFloat
  - XML_setString
