category: Data
subcategory: Primitive
description: "
Data type for floating-point numbers, a number that has a decimal point. 
<br/>
Floats are not precise, so avoid adding small values (such as 0.0001), as these  may not always increment because of rounding error. If you want to increment a value in small intervals, use an int, and divide by a float value before using it. (See above example.)<br />
<br />
"
syntax: "<c>var</c> = <c>value</c>"
parameters:
  - label: 'var'
    description: "variable name referencing the float"
  - label: 'value'
    description: "any floating-point value"
related:
  - int
