category: Structure
subcategory: 
description: "
Provides access to an object's methods and data. An object is one instance of a class and may contain both methods (object functions) and data (object variables and constants), as specified in the class definition. The dot operator directs the program to the information encapsulated within an object.
"
syntax: "	<c>object</c>.<c>method()</c><br/>\n<c>object</c>.<c>data</c>"
parameters:
  - label: 'object'
    description: "the object to be accessed"
  - label: 'method()'
    description: "a method encapsulated in the object"
  - label: 'data'
    description: "a variable or constant encapsulated in the object"
related:
  - Object
