category: PShape
subcategory: Method
description: "
Rotates a shape around the z-axis the amount specified by the <b>angle</b> parameter. Angles should be specified in radians (values from 0 to TWO_PI) or converted to radians with the <b>radians()</b> method.
<br /><br />
Shapes are always rotated around the upper-left corner of their bounding box. Positive numbers rotate objects in a clockwise direction. Subsequent calls to the method accumulates the effect. For example, calling <b>rotateZ(HALF_PI)</b> and then <b>rotateZ(HALF_PI)</b> is the same as <b>rotateZ(PI)</b>. This transformation is applied directly to the shape, it's not refreshed each time <b>draw()</b> is run. 
<br /><br />
This method requires a 3D renderer. You need to use P3D as a third parameter for the <b>size()</b> function as shown in the example above.
"
syntax: "<c>sh</c>.rotateZ(<c>angle</c>)"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
  - label: 'angle'
    description: "float: angle of rotation specified in radians"
related:
  - rotate
  - rotateX
  - rotateY
  - scale
  - translate
  - resetMatrix
