category: Transform
subcategory: 
description: "
Pops the current transformation matrix off the matrix stack. Understanding pushing and popping requires understanding the concept of a matrix stack. The <b>pushMatrix()</b> function saves the current coordinate system to the stack and <b>popMatrix()</b> restores the prior coordinate system. <b>pushMatrix()</b> and <b>popMatrix()</b> are used in conjuction with the other transformation functions and may be embedded to control the scope of the transformations.
"
syntax: "popMatrix()"
related:
  - pushMatrix
