category: Structure
subcategory: 
description: "

Index brackets (<b>[]</b>) have many uses in Python. First, they are used to
define \"list literals,\" allowing you to declare a list and its contents in your
program. Index brackets are also used to write expressions that evaluate to a
single item within a list, or a single character in a string.<br/><br/>

For lists and other mutable sequences (but not strings), you can overwrite a
value at a particular index using the assignment operator (<b>=</b>).<br/><br/>

Negative numbers inside of index brackets cause Python to start counting
from the end of the sequence, instead of from the beginning. For example,
the expression <b>x[-1]</b> evaluates to the last item of list <b>x</b>,
<b>x[-2]</b> evaluates to the second-to-last item of list <b>x</b>, and
so forth.<br/><br/>

Finally, index brackets are used to retrieve or set the value for a given key
in a dictionary. For example, the expression <b>x[a]</b> evaluates to
whatever the value for key <b>a</b> is in dictionary <b>x</b>. The
statement <b>x[a] = b</b> will set the value for key <b>a</b> in dictionary
<b>x</b> to a new value <b>b</b> (overwriting any existing value).<br/><br/>

Specifying an index beyond the bounds of the sequence raises an
<b>IndexError</b> exception. Attempting to retrieve the value for a
key that does not exist in a dictionary raises a <b>KeyError</b> exception.
<br/><br/>

"
syntax: "	[<c>elem0, ..., elemN</c>]\n	<c>sequence</c>[<c>index</c>]\n	<c>sequence</c>[<c>index</c>] = <c>expr</c>\n	<c>dict</c>[<c>key</c>]\n	<c>dict</c>[<c>key</c>] = <c>value</c>"
parameters:
  - label: 'elem0, ..., elemN'
    description: "list of elements, separated by commas, used to initialize a list"
  - label: 'sequence'
    description: "a list, string or other sequence"
  - label: 'index'
    description: "an integer index"
  - label: 'expr'
    description: "an expression, the result of which will be assigned to the given index in the sequence"
  - label: 'dict'
    description: "a dictionary"
  - label: 'key'
    description: "the key whose value you want to retrieve"
  - label: 'value'
    description: "a new value for the given key"
related:
  - slice
  - curlybraces
