category: Data
subcategory: Conversion
description: "
Returns the string representation of primitive datatypes and arrays. For example the integer 3 will return the string \"3\", the float -12.6 will return the string \"-12.6\", and a Boolean value True will return the string \"True\".
"
syntax: "	str(var)"
parameters:
  - label: 'var'
    description: "any int, float, character, string, boolean"
related:
  - string
  - string_formatting
  - string_find
  - string_strip
  - string_join
  - string_replace
