category: Data
subcategory: Composite
description: "
A string is a sequence of characters. Python's built-in string class includes
methods for searching strings, transforming strings, and checking to see if a
string has particular characteristics. Strings are defined inside either double
quotes (\"ABC\") or single quotes ('ABC').
<br/><br/>

Because strings are defined between quotation marks, to include such marks
within the string itself you must use the <b>&#92;</b> (backslash) character.
(See the second example above.)  This is known as an <em>escape
	sequence</em>. Other escape sequences include <b>&#92;t</b> for the tab
character and <b>&#92;n</b> for new line. Because backslash is the escape
character, to include a single backslash within a string, you must use two
consecutive backslashes, as in: <b>&#92;&#92;</b>
<br/><br/>

Normally, strings in your program must be written entirely on one line. If you
want to include a chunk of text in your program that spans multiple lines, you
can use triple quotes (either <b>\"\"\"</b> or <b>'''</b>). (See the third example
above.)
<br/><br/>

There are more string methods than those linked from this page. Additional documentation is located online in the <a href=\"https://docs.python.org/2/library/stdtypes.html#string-methods\">official Python documentation</a>.

"
syntax: "	'str'\n	\"str\"\n	\"\"\"\n	str\n	\"\"\""
parameters:
  - label: 'str'
    description: "any string of characters"
related:
  - string_formatting
  - string_find
  - string_strip
  - string_join
  - string_split
  - string_replace
