category: Math
subcategory: Trigonometry
description: "
Calculates the sine of an angle. This function expects the values of the <b>angle</b> parameter to be provided in radians (values from 0 to 6.28). Values are returned in the range -1 to 1.
"
syntax: "sin(<c>angle</c>)"
parameters:
  - label: 'angle'
    description: "float: an angle in radians"
related:
  - cos
  - tan
  - radians
