category: Shape
subcategory: Attributes
description: "
Sets the style for rendering line endings. These ends are either squared, extended, or rounded, each of which specified with the corresponding parameters: SQUARE, PROJECT, and ROUND. The default cap is ROUND.
"
syntax: "	strokeMode(mode);"
parameters:
  - label: 'mode'
    description: "int: either ROUND, SQUARE or PROJECT"
related:
  - stroke
  - strokeWeight
  - strokeJoin
  - size
