category: Data
subcategory: List Methods
description: "
Sort the elements of a list in place. Numbers are sorted by their value, and
strings are sorted in (case-sensitive) alphabetical order. If the keyword
argument <b>reverse</b> is given and set to <b>True</b>, the list is sorted in
reverse.
<br/><br/>

An optional keyword parameter <b>key</b> specifies a function that will be
called for each item of the list before comparing it in the sorting process.
This function takes a single parameter and should return the value that Python
should use for the specified value when sorting the list. You can use this
functionality to easily build (as in the example above) a case-insensitive
sort.

"
syntax: "<c>a</c>.sort()"
parameters:
  - label: 'a'
    description: "the list to sort"
  - label: 'fn'
    description: "a function, called automatically for each list element"
related:
  - list_insert
  - list_pop
  - list_append
  - list_index
  - sorted
