category: Shape
subcategory: 2D Primitives
description: "
A triangle is a plane created by connecting three points. The first two arguments specify the first point, the middle two arguments specify the second point, and the last two arguments specify the third point. 
"
syntax: ""
related:
  - PShape_beginShape
  - rect
