category: Input
subcategory: Keyboard
description: "
The <b>keyReleased()</b> function is called once every time a key is released. The key that was released will be stored in the <b>key</b> variable. See <b>key</b> and <b>keyReleased</b> for more information.
<br/><br/>
Mouse and keyboard events only work when a program has <b>draw()</b>. Without <b>draw()</b>, the code is only run once and then stops listening for events.
"
syntax: "keyReleased()\nkeyReleased(event)"
parameters:
  - label: 'event'
    description: "MouseEvent: the MouseEvent"
related:
  - key
  - keyCode
  - keyPressed_var
  - keyPressed
