category: PFont
subcategory: Method
description: "
Gets a list of the fonts installed on the system. The data is returned as a String list. This list provides the names of each font for input into <b>createFont()</b>, which allows Processing to dynamically format fonts.
"
syntax: ""
