category: Output
subcategory: Text Area
description: "
	The <b>println()</b> function writes to the console area, the black rectangle at the bottom of the Processing environment. This function is often helpful for looking at the data a program is producing.<br/>
<br />
Using <b>println()</b> on an object will output a string representation of that object, as determined by its internal <b>__str__</b> and <b>__repr__</b> methods (<a href=\"http://stackoverflow.com/a/2626364\">more information here</a>).<br/>
<br/>
In Python Mode, <b>print()</b> and <b>println()</b> are functionally identical.
"
syntax: "println(<c>what</c>)"
parameters:
  - label: 'what'
    description: "data to print to console"
related:
  - PrintWriter_println
