category: Table
subcategory: Method
description: "
Finds the rows in the <b>Table</b> that contain the value provided, and returns references to those rows.  Returns an iterator, so <b>for</b> must be used to iterate through all the rows, as shown in the example above. The column to search may be specified by either its ID or title.
"
syntax: ".findRows(<c>value</c>, <c>column</c>)\n.findRows(<c>value</c>, <c>columnName</c>)"
parameters:
  - label: 'value'
    description: "String: the value to match"
  - label: 'column'
    description: "int: ID number of the column to search"
  - label: 'columnName'
    description: "String: title of the column to search"
related:
  - Table_getRow
  - Table_rows
  - Table_findRow
  - Table_matchRow
  - Table_matchRows
