category: Output
subcategory: Files
description: "
As the opposite of <b>loadBytes()</b>, this function will write an entire list of bytes to a file. The data is saved in binary format. This file is saved to the sketch's folder, which is opened by selecting \"Show Sketch Folder\" from the \"Sketch\" menu. Alternatively, the files can be saved to any location on the computer by using an absolute path (something that starts with / on Unix and Linux, or a drive letter on Windows).
"
syntax: "saveBytes(<c>filename</c>, <c>data</c>)"
parameters:
  - label: 'filename'
    description: "String: name of the file to write to"
  - label: 'data'
    description: "list of bytes to be written"
related:
  - loadStrings
  - loadBytes
  - saveStrings
