language: java

services: docker

jdk:
  - oraclejdk8

before_install:
  - .ci/init.sh

install:
  - sudo apt-get install ant-optional
  - ant info
  - ant try
  - ant package

script:
  - docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci
  # See https://askubuntu.com/a/693533
  - xvfb-run -a -s "-screen 0 1024x768x24" ant report
