language: java

services: docker

jdk:
  - oraclejdk8

before_install:
  - .ci/init.sh

install:
  - ant info
  - ant try
  - ant package

script:
  - docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci
# E2e tests always fail in CI.
#   - ant report

# after_success:
#   - curl https://secure.central.sonatype.com/maven2/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar > codacy-coverage-reporter-assembly.jar
#   - java -cp codacy-coverage-reporter-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r test-output/site/jacoco/report.xml
