language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      jdk: oraclejdk8
      services: docker
    - os: osx
  allow_failures:
    - os: osx

before_install:
  - .ci/init.sh

install:
  - ant info
  - ant try
  - ant package

script:
  - .ci/check-and-test.sh
