language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx

services: docker

before_install:
  - .ci/init.sh

install:
  - ant info
  - ant try
  - ant package

script:
  - .ci/check-and-test.sh
