category: Data
subcategory: Dictionary Methods
description: "
\"Updates\" a dictionary with the contents of a second dictionary. Any key/value
pairs present in the second dictionary will be added to the first. If the
second dictionary contains a key present in the first dictionary, its value
will be overwritten with the value from the second dictionary.
"
syntax: "	<c>dict1</c>.update(<c>dict2</c>)"
parameters:
  - label: 'dict1'
    description: "The dictionary to be updated."
  - label: 'dict2'
    description: "The source dictionary for the update, where new key/value pairs will be drawn from."
related:
  - dictionary
