category: Data
subcategory: String Functions
description: "
This function is used to apply a regular expression to a piece of text, and return matching groups (elements found inside parentheses) as a String array. If there are no matches, a None value will be returned. If no groups are specified in the regular expression, but the sequence matches, an array of length 1 (with the matched text as the first element of the array) will be returned.<br/>
<br/>
To use the function, first check to see if the result is None. If the result is None, then the sequence did not match at all. If the sequence did match, an array is returned.<br/>
<br/>
If there are groups (specified by sets of parentheses) in the regular expression, then the contents of each will be returned in the array. Element [0] of a regular expression match returns the entire matching string, and the match groups start at element [1] (the first group is [1], the second [2], and so on).<br/>
<br/>
The syntax can be found in the reference for Java's <a href=\"http://download.oracle.com/javase/6/docs/api/\">Pattern</a> class. For regular expression syntax, read the <a href=\"http://download.oracle.com/javase/tutorial/essential/regex/\">Java Tutorial</a> on the topic.
"
syntax: "match(<c>str</c>, <c>regexp</c>)"
parameters:
  - label: 'str'
    description: "String: the String to be searched"
  - label: 'regexp'
    description: "String: the regexp to be used for matching"
related:
  - matchAll
  - string_split
  - string_join
