category: PShape
subcategory: Method
description: "
Returns a Boolean value \"True\" if the image is set to be visible, \"False\" if not. This value can be modified with the <b>setVisible()</b> method.<br/>
<br/>
The default visibility of a shape is usually controlled by whatever program created the SVG file. For instance, this parameter is controlled by showing or hiding the shape in the layers palette in Adobe Illustrator.
"
syntax: "sh.isVisible()"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
related:
  - PShape_setVisible
