category: Table
subcategory: Method
description: "
Removes any of the specified characters (or \"tokens\").  The example above removes all commas, dollar signs, and spaces from the table.<br>
<br>
If no column is specified, then the values in all columns and rows are processed.  A specific column may be referenced by either its ID or title.
"
syntax: ".removeTokens(<c>tokens</c>)\n.removeTokens(<c>tokens</c>, <c>column</c>)\n.removeTokens(<c>tokens</c>, <c>columnName</c>)"
parameters:
  - label: 'tokens'
    description: "String: a list of individual characters to be removed"
  - label: 'column'
    description: "int: ID number of the column to process"
  - label: 'columnName'
    description: "String: title of the column to process"
