category: PVector
subcategory: Method
description: "
Adds x, y, and z components to a vector, adds one vector to another, or adds two independent vectors together. The version of the method that adds two vectors together is a static method and returns a PVector, the others have no return value -- they act directly on the vector. See the examples for more context.
"
syntax: ".add(<c>v</c>)\n.add(<c>x</c>, <c>y</c>, <c>z</c>)\n.add(<c>v1</c>, <c>v2</c>)\n.add(<c>v1</c>, <c>v2</c>, <c>target</c>)"
parameters:
  - label: 'v'
    description: "PVector: the vector to be added"
  - label: 'x'
    description: "float: x component of the vector"
  - label: 'y'
    description: "float: y component of the vector"
  - label: 'z'
    description: "float: z component of the vector"
  - label: 'v1'
    description: "PVector: a vector"
  - label: 'v2'
    description: "PVector: another vector"
  - label: 'target'
    description: "PVector: the target vector (if null, a new vector will be created)"
