category: Control
subcategory: Relational Operators
description: "
Tests if the value on the left is larger than the value on the right or if the values are equivalent. 
"
syntax: "<c>value1</c> &gt;= <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int or float"
  - label: 'value2'
    description: "int or float"
related:
  - greaterthan
  - lessthan
  - lessthanorequalto
  - equality
  - inequality
