category: Image
subcategory: Pixels
description: "
Changes the color of any pixel, or writes an image directly to the display window.<br />
<br />
The <b>x</b> and <b>y</b> parameters specify the pixel to change and the <b>c</b> parameter specifies the color value. The <b>c</b> parameter is interpreted according to the current color mode.  (The default color mode is RGB values from 0 to 255.)  When setting an image, the <b>x</b> and <b>y</b> parameters define the coordinates for the upper-left corner of the image, regardless of the current <b>imageMode()</b>.
<br /><br />
Setting the color of a single pixel with <b>set(x, y)</b> is easy, but not as fast as putting the data directly into <b>pixels</b>. The equivalent statement to <b>set(x, y, #000000)</b> using <b>pixels</b> is <b>pixels[y*width+x] = #000000</b>. See the reference for <a href=\"pixels.html\">pixels</a> for more information.
"
syntax: "set(<c>x</c>, <c>y</c>, <c>c</c>)\nset(<c>x</c>, <c>y</c>, <c>img</c>)"
parameters:
  - label: 'x'
    description: "int: x-coordinate of the pixel"
  - label: 'y'
    description: "int: y-coordinate of the pixel"
  - label: 'c'
    description: "int: any value of the color datatype"
  - label: 'img'
    description: "PImage: image to copy into the original image"
related:
  - pixels
