category: Output
subcategory: Files
description: "
Writes the contents of an XML object to a file. By default, this file is saved to the sketch's folder. This folder is opened by selecting \"Show Sketch Folder\" from the \"Sketch\" menu.<br/>
<br/>
Alternatively, the file can be saved to any location on the computer by using an absolute path (something that starts with / on Unix and Linux, or a drive letter on Windows).<br/>
<br/>
All files loaded and saved by the Processing API use UTF-8 encoding.
"
syntax: "saveXML(<c>xml</c>, <c>filename</c>)\nsaveXML(<c>xml</c>, <c>filename</c>, <c>options</c>)"
parameters:
  - label: 'xml'
    description: "XML: the XML object to save to disk"
  - label: 'filename'
    description: "String: name of the file to write to"
related:
  - XML
  - loadXML
  - parseXML
