category: Data
subcategory: Dictionary Methods
description: "
Returns a list of all values in the dictionary (without reference to their
keys).<br/><br/>

Note that because of the nature of the dictionary data structure, 
the return value of <b>values()</b> will be in arbitrary order.
"
syntax: "	<c>dict</c>.values()"
parameters:
  - label: 'dict'
    description: "The dictionary whose values will be returned."
related:
  - dictionary
  - dict_keys
