category: Table
subcategory: Method
description: "
Use <b>addColumn()</b> to add a new column to a <b>Table</b> object.  Typically, you will want to specify a title, so the column may be easily referenced later by name.  (If no title is specified, the new column's title will be null.)  A column type may also be specified, in which case all values stored in this column must be of the same type (e.g., Table.INT or Table.FLOAT).  If no type is specified, the default type of STRING is used.
"
syntax: ".addColumn()\n.addColumn(<c>title</c>)\n.addColumn(<c>title</c>, <c>type</c>)"
parameters:
  - label: 'title'
    description: "String: the title to be used for the new column"
  - label: 'type'
    description: "int: the type to be used for the new column: INT, LONG, FLOAT, DOUBLE, STRING, or CATEGORY"
related:
  - Table_removeColumn
