category: Transform
subcategory: 
description: "
Specifies an amount to displace objects within the display window. The <b>x</b> parameter specifies left/right translation, the <b>y</b> parameter specifies up/down translation, and the <b>z</b> parameter specifies translations toward/away from the screen. Using this function with the <b>z</b> parameter requires using P3D as a parameter in combination with size as shown in the above example.
<br/><br/>
Transformations are cumulative and apply to everything that happens after and subsequent calls to the function accumulates the effect. For example, calling <b>translate(50, 0)</b> and then <b>translate(20, 0)</b> is the same as <b>translate(70, 0)</b>. If <b>translate()</b> is called within <b>draw()</b>, the transformation is reset when the loop begins again. This function can be further controlled by using <b>pushMatrix()</b> and <b>popMatrix()</b>.
"
syntax: ""
related:
  - popMatrix
  - pushMatrix
  - rotate
  - rotateX
  - rotateY
  - rotateZ
  - scale
