category: Shape
subcategory: Vertex
description: "
Specifies vertex coordinates for curves. This function may only be used between <b>beginShape()</b> and <b>endShape()</b> and only when there is no MODE parameter specified to <b>beginShape()</b>. The first and last points in a series of <b>curveVertex()</b> lines will be used to guide the beginning and end of a the curve. A minimum of four points is required to draw a tiny curve between the second and third points. Adding a fifth point with <b>curveVertex()</b> will draw the curve between the second, third, and fourth points. The <b>curveVertex()</b> function is an implementation of Catmull-Rom splines. Using the 3D version requires rendering with P3D (see the Environment reference for more information).
"
syntax: "curveVertex(<c>x</c>, <c>y</c>)\ncurveVertex(<c>x</c>, <c>y</c>, <c>z</c>)"
parameters:
  - label: 'x'
    description: "float: the x-coordinate of the vertex"
  - label: 'y'
    description: "float: the y-coordinate of the vertex"
  - label: 'z'
    description: "float: the z-coordinate of the vertex"
related:
  - curve
  - PShape_beginShape
  - PShape_endShape
  - vertex
  - bezier
  - quadraticVertex
