category: PVector
subcategory: Method
description: "
Multiplies a vector by a scalar.  The version of the method that uses a float acts directly on the vector upon which it is called (as in the first example above), and therefore has no return value.  The versions that receive both a PVector and a float as arugments are static methods, and each returns a new PVector that is the result of the multiplication operation.  Both examples above produce the same visual output.
"
syntax: ".mult(<c>n</c>)\n.mult(<c>v</c>, <c>n</c>)\n.mult(<c>v</c>, <c>n</c>, <c>target</c>)"
parameters:
  - label: 'n'
    description: "float: the number to multiply with the vector"
  - label: 'v'
    description: "PVector: the vector to multiply by the scalar"
  - label: 'target'
    description: "PVector: PVector in which to store the result"
