category: Structure
subcategory: 
description: "
Reserved word representing the logical value \"False\". Only variables of type <b>Boolean</b> may be assigned the value <b>False</b>.
"
syntax: ""
related:
  - True
  - Boolean
