category: Color
subcategory: Creating & Reading
description: "
Calculates a color or colors between two color at a specific increment. The <b>amt</b> parameter is the amount to interpolate between the two values where 0.0 equal to the first point, 0.1 is very near the first point, 0.5 is halfway in between, etc. 
<br />
An amount below 0 will be treated as 0. Likewise, amounts above 1 will be capped at 1. This is different from the behavior of lerp(), but necessary because otherwise numbers outside the range will produce strange and unexpected colors.
"
syntax: "lerpColor(<c>c1</c>, <c>c2</c>, <c>amt</c>)"
parameters:
  - label: 'c1'
    description: "int: interpolate from this color"
  - label: 'c2'
    description: "int: interpolate to this color"
  - label: 'amt'
    description: "float: between 0.0 and 1.0"
related:
  - color
  - PVector_lerp
