category: Input
subcategory: Files
description: "
Reads the contents of a file or URL and creates an Table object with its values. If a file is specified, it must be located in the sketch's \"data\" folder. The filename parameter can also be a URL to a file found online.  By default, the file is assumed to be comma-separated (in CSV format).  To use tab-separated data, include \"tsv\" in the options parameter.<br/>
<br/>
If the file contains a header row, include \"header\" in the options parameter.  If the file does not have a header row, then simply omit the \"header\" option.<br/>
<br/>
When specifying both a header and the file type, separate the options with commas, as in: <b>loadTable(\"data.csv\", \"header, tsv\")</b><br/>
<br/>
All files loaded and saved by the Processing API use UTF-8 encoding.
"
syntax: "loadTable(<c>filename</c>)\nloadTable(<c>filename</c>, <c>options</c>)"
parameters:
  - label: 'filename'
    description: "String: name of a file in the data folder or a URL."
related:
  - Table
  - saveTable
  - loadBytes
  - loadStrings
  - loadXML
