category: Color
subcategory: Setting
description: "
Sets the color used to draw lines and borders around shapes. This color is either specified in terms of the RGB or HSB color depending on the current <b>colorMode()</b> (the default color space is RGB, with each value in the range from 0 to 255). 
<br/> <br/>
When using hexadecimal notation to specify a color, use \"#\" or \"0x\" before the values (e.g. #CCFFAA, 0xFFCCFFAA). The # syntax uses six digits to specify a color (the way colors are specified in HTML and CSS). When using the hexadecimal notation starting with \"0x\", the hexadecimal value must be specified with eight characters; the first two characters define the alpha component and the remainder the red, green, and blue components. 
<br/> <br/>
The value for the gray parameter must be less than or equal to the current maximum value as specified by <b>colorMode()</b>. The default maximum value is 255.
<br/> <br/>
When drawing in 2D with the default renderer, you may need <b>hint(ENABLE_STROKE_PURE)</b> to improve drawing quality (at the expense of performance). See the hint() documentation for more details.
"
syntax: "	stroke(gs)\n	stroke(r, g, b)"
parameters:
  - label: 'gs'
    description: "int: grayscale value for the stroke"
  - label: 'r'
    description: "int: red value for the stroke"
  - label: 'g'
    description: "int: green value for the stroke"
  - label: 'b'
    description: "int: blue value for the stroke"
related:
  - noStroke
  - strokeWeight
  - strokeJoin
  - strokeCap
  - fill
  - noFill
  - tint
  - background
  - colorMode
