category: XMLElement
subcategory: Method
description: "
Returns an attribute value of the element as a String. If the <b>defaultValue</b> parameter is specified and the attribute doesn't exist, then <b>defaultValue</b> is returned. If no <b>defaultValue</b> is specified and the attribute doesn't exist, null is returned.
"
syntax: ".getString(name)\n.getString(name, defaultValue)\n"
