category: Shape
subcategory: Loading & Displaying
description: "
Modifies the location from which shapes draw. The default mode is <b>shapeMode(CORNER)</b>, which specifies the location to be the upper left corner of the shape and uses the third and fourth parameters of <b>shape()</b> to specify the width and height. The syntax <b>shapeMode(CORNERS)</b> uses the first and second parameters of <b>shape()</b> to set the location of one corner and uses the third and fourth parameters to set the opposite corner. The syntax <b>shapeMode(CENTER)</b> draws the shape from its center point and uses the third and forth parameters of <b>shape()</b> to specify the width and height. The parameter must be written in \"ALL CAPS\" because Processing is a case sensitive language.
"
syntax: "shapeMode(<c>mode</c>)"
parameters:
  - label: 'mode'
    description: "int: either CORNER, CORNERS, CENTER"
related:
  - PShape
  - shape
  - rectMode
