category: Math
subcategory: Calculation
description: "
Re-maps a number from one range to another.<br/>
<br/>
In the first example above, the number 50 is converted from a value in the range of 0 to the width of the window (which is the default value of 100) into a value that ranges from the left edge of the window (0) to half the width of the window (50).<br/>
<br/>
As shown in the second example, numbers outside of the range are not clamped to the minimum and maximum parameters values, because out-of-range values are often intentional and useful. <br />
<br />
The third example shows how this function may be applied to user input. 
"
syntax: "map(<c>value</c>, <c>start1</c>, <c>stop1</c>, <c>start2</c>, <c>stop2</c>)"
parameters:
  - label: 'value'
    description: "float: the incoming value to be converted"
  - label: 'start1'
    description: "float: lower bound of the value's current range"
  - label: 'stop1'
    description: "float: upper bound of the value's current range"
  - label: 'start2'
    description: "float: lower bound of the value's target range"
  - label: 'stop2'
    description: "float: upper bound of the value's target range"
related:
  - norm
  - PVector_lerp
