category: TableRow
subcategory: Method
description: "
Stores a string value in the <b>TableRow</b>'s specified column. The column may be specified by either its ID or title.
"
syntax: ".setString(<c>column</c>, <c>value</c>)\n.setString(<c>columnName</c>, <c>value</c>)"
parameters:
  - label: 'column'
    description: "int: ID number of the target column"
  - label: 'value'
    description: "String: value to assign"
  - label: 'columnName'
    description: "String: title of the target column"
related:
  - XML_setInt
  - XML_setFloat
  - XML_getInt
  - XML_getFloat
  - XML_getString
  - Table_getStringColumn
