category: Input
subcategory: Mouse
description: "
The <b>mouseWheel()</b> function returns positive values when the mouse wheel is rotated down (toward the user), and negative values for the other direction (up or away from the user). On OS X with \"natural\" scrolling enabled, the values are opposite.
<br/><br/>
Mouse and keyboard events only work when a program has <b>draw()</b>. Without <b>draw()</b>, the code is only run once and then stops listening for events.
"
syntax: "mouseWheel(event)"
parameters:
  - label: 'event'
    description: "MouseEvent: the MouseEvent"
related:
  - mouseX
  - mouseY
  - pmouseX
  - pmouseY
  - mousePressed_var
  - mousePressed
  - mouseReleased
  - mouseClicked
  - mouseMoved
  - mouseDragged
  - mouseButton
