category: Data
subcategory: Primitive
description: "
Datatype for the Boolean values <b>True</b> and <b>False</b>. It is common to use <b>boolean</b> values with control statements to determine the flow of a program. The first time a variable is written, it must be declared with a statement expressing its datatype.
"
syntax: "<c>var</c> = <c>booleanValue</c>"
parameters:
  - label: 'var'
    description: "variable name referencing the value"
  - label: 'booleanValue'
    description: "True or False"
related:
  - True
  - False
