category: Constants
subcategory: 
description: "
HALF_PI is a mathematical constant with the value 1.57079632679489661923. It is half the ratio of the circumference of a circle to its diameter. It is useful in combination with the trigonometric functions <b>sin()</b> and <b>cos()</b>. 
"
syntax: ""
related:
  - PI
  - TWO_PI
  - TAU
  - QUARTER_PI
