category: Math
subcategory: Operators
description: "
Calculates the remainder when one number is divided by another. For example, when 52.1 is divided by 10, the divisor (10) goes into the dividend (52.1) five times (5 * 10 == 50), and there is a remainder of 2.1 (52.1 - 50 == 2.1). Thus, <strong>52.1 % 10</strong> produces <strong>2.1</strong>.<br/>
<br/>
Note that when the divisor is greater than the dividend, the remainder constitutes the value of the entire dividend. That is, a number cannot be divided by any number larger than itself. For example, when 9 is divided by 10, the result is zero with a remainder of 9. Thus, <strong>9 % 10</strong> produces <strong>9</strong>.<br/>
<br/>
Modulo is extremely useful for keeping numbers within a boundary such as keeping a shape on the screen. (See the second example above.)
"
syntax: "<c>value1</c> % <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int or float"
  - label: 'value2'
    description: "int or float"
related:
  - divide
