category: Data
subcategory: List Methods
description: "
This method removes and returns an element of the list from the given index. If
no index is given, the last element is removed and returned.
"
syntax: "<c>a</c>.pop()\n<c>a</c>.pop(<c>i</c>)"
parameters:
  - label: 'a'
    description: "List from which to pop."
  - label: 'i'
    description: "Index of element to pop."
related:
  - list_insert
  - list_append
  - list_reverse
  - list_index
