category: Structure
subcategory: 
description: "
There are three different assignment operators: two of them have leftwards and rightwards forms.<br />
<br />
The operators <- and = assign into the environment in which they are evaluated. The operator <- can be used anywhere, whereas the operator = is only allowed at the top level (e.g., in the complete expression typed at the command prompt) or as one of the subexpressions in a braced list of expressions.<br />
<br />
The operators <<- and ->> are normally only used in functions, and cause a search to be made through parent environments for an existing definition of the variable being assigned. If such a variable is found (and its binding is not locked) then its value is redefined, otherwise assignment takes place in the global environment. Note that their semantics differ from that in the S language, but are useful in conjunction with the scoping rules of R. See ‘The R Language Definition’ manual for further details and examples.<br />
<br />
In all the assignment operator expressions, x can be a name or an expression defining a part of an object to be replaced (e.g., z[[1]]). A syntactic name does not need to be quoted, though it can be (preferably by backticks).<br />
<br />
The leftwards forms of assignment <- = <<- group right to left, the other from left to right.<br />
"
syntax: "x <- value\nx <<- value\nvalue -> x\nvalue ->> x\n\nx = value"
parameters:
  - label: 'x'
    description: "a variable name (possibly quoted)."
  - label: 'value'
    description: "a value to be assigned to x."
