category: Data
subcategory: String Methods
description: "
Returns a copy of a string, with all uppercase characters converted to
lowercase.
"
syntax: "	str.lower()"
parameters:
  - label: 'str'
    description: "String: any string of characters."
related:
  - string
  - string_formatting
  - string_find
  - string_strip
  - string_join
  - string_replace
