category: Shape
subcategory: Curves
description: "
Sets the resolution at which Beziers display. The default value is 20. This function is only useful when using the <b>P3D</b> renderer; the default <b>P2D</b> renderer does not use this information.
"
syntax: "bezierDetail(<c>detail</c>)"
parameters:
  - label: 'detail'
    description: "int: resolution of the curves"
related:
  - curve
  - curveVertex
  - curveTightness
