category: Math
subcategory: Trigonometry
description: "
Converts a radian measurement to its corresponding value in degrees. Radians and degrees are two ways of measuring the same thing. There are 360 degrees in a circle and 2*PI radians in a circle. For example, 90&deg; = PI/2 = 1.5707964. All trigonometric functions in Processing require their parameters to be specified in radians.
"
syntax: "degrees(<c>radians</c>)"
parameters:
  - label: 'radians'
    description: "float: radian value to convert to degrees"
related:
  - radians
