category: XMLElement
subcategory: Method
description: "
Sets the content of an element's attribute as a float.  A String specifies the attribute name, while the float specifies the new content.
"
syntax: ".setFloat(name, value)\n"
