category: Structure
subcategory: 
description: "
The keyword <b>add_library</b> is used to load a library into a Processing sketch. 
A library is one or more classes that are grouped together to extend the capabilities of Processing. 
"
syntax: "add_library(<c>libraryName</c>)"
parameters:
  - label: 'libraryName'
    description: "string: the name of the library to load (e.g. \"pdf\")"
