category: Shape
subcategory: Vertex
description: "
The <b>endShape()</b> function is the companion to <b>beginShape()</b> and may only be called after <b>beginShape()</b>. When <b>endshape()</b> is called, all of image data defined since the previous call to <b>beginShape()</b> is written into the image buffer. The constant CLOSE as the value for the MODE parameter to close the shape (to connect the beginning and the end). 
"
syntax: "endShape()\nendShape(mode)"
parameters:
  - label: 'mode'
    description: "int: use CLOSE to close the shape"
related:
  - PShape
  - PShape_beginShape
