category: Table
subcategory: Method
description: "
Use <b>addRow()</b> to add a new row of data to a <b>Table</b> object.  By default, an empty row is created.  Typically, you would store a reference to the new row in a <b>TableRow</b> object (see <b>newRow</b> in the example above), and then set individual values using <b>setInt()</b>, <b>setFloat()</b>, or <b>setString()</b>.  If a <b>TableRow</b> object is included as a parameter, then that row is duplicated and added to the table.
"
syntax: ".addRow()\n.addRow(source)"
parameters:
  - label: 'source'
    description: "TableRow: a reference to the original row to be duplicated"
related:
  - Table_removeRow
  - Table_clearRows
