category: Control
subcategory: Conditionals
description: "
Allows the program to make a decision about which code to execute. If the <b>test</b> evaluates to <b>True</b>, the statements enclosed within the block are executed and if the <b>test</b> evaluates to <b>False</b> the statements are not executed.
"
syntax: "if <c>test</c>: \n  <c>statements</c> "
parameters:
  - label: 'test'
    description: "any valid expression that evaluates to True or False"
  - label: 'statements'
    description: "one or more statements to be executed"
related:
  - else
