category: Image
subcategory: Loading & Displaying
description: "
Loads an image into a variable of type <b>PImage</b>. Four types of images ( <b>.gif</b>, <b>.jpg</b>, <b>.tga</b>, <b>.png</b>) images may be loaded. To load correctly, images must be located in the data directory of the current sketch.<br>
<br />
In most cases, load all images in <b>setup()</b> to preload them at the start of the program. Loading images inside <b>draw()</b> will reduce the speed of a program. Images cannot be loaded outside <b>setup()</b> unless they're inside a function that's called after <b>setup()</b> has already run.<br>
<br/>
Alternatively, the file maybe be loaded from anywhere on the local computer using an absolute path (something that starts with / on Unix and Linux, or a drive letter on Windows), or the filename parameter can be a URL for a file found on a network.<br />
<br />
If the file is not available or an error occurs, <b>null</b> will be returned and an error message will be printed to the console. The error message does not halt the program, however the null value may cause a NullPointerException if your code does not check whether the value returned is null.<br/>
<br />
The <b>extension</b> parameter is used to determine the image type in cases where the image filename does not end with a proper extension. Specify the extension as the second parameter to <b>loadImage()</b>, as shown in the third example on this page.<br/> 
<br/>
Depending on the type of error, a <b>PImage</b> object may still be returned, but the width and height of the image will be set to -1. This happens if bad image data is returned or cannot be decoded properly. Sometimes this happens with image URLs that produce a 403 error or that redirect to a password prompt, because <b>loadImage()</b> will attempt to interpret the HTML as image data.
"
syntax: "loadImage(<c>filename</c>)\nloadImage(<c>filename</c>, <c>extension</c>)"
parameters:
  - label: 'filename'
    description: "String: name of file to load, can be .gif, .jpg, .tga, or a handful of other image types depending on your platform"
  - label: 'extension'
    description: "String: type of image to load, for example \"png\", \"gif\", \"jpg\""
related:
  - PImage
  - image
  - imageMode
  - background
