category: PShape
subcategory: Method
description: "
Replaces the current matrix of a shape with the identity matrix. The equivalent function in OpenGL is <b>glLoadIdentity()</b>. 
"
syntax: "resetMatrix()"
related:
  - rotate
  - scale
  - translate
