category: Structure
subcategory: 
description: "
Explanatory notes embedded within the code. Comments are used to remind yourself and to inform others about the function of your program. Multiline comments are used for large text descriptions of code or to comment out chunks of code while debugging applications. Note that in Python mode you can make multiline comments with single quotes '''like this''' or with double quotes \"\"\"like this\"\"\". Comments are ignored by the interpreter.  
"
syntax: "\"\"\"\n  <c>comment</c>\n\"\"\"\nor \n'''\n   <c>comment</c>\n'''"
parameters:
  - label: 'comment'
    description: "any sequence of characters"
related:
  - comment
