category: Data
subcategory: Conversion
description: "
Converts a string representation of a binary number to its equivalent integer value. For example, <b>unbinary(\"00001000\")</b> will return 8.
"
syntax: "	unbinary(str)"
parameters:
  - label: 'str'
    description: "str: string representation of a binary number"
related:
  - binary
  - hex
  - unhex
