category: Shape
subcategory: Vertex
description: "
Specifies vertex coordinates for quadratic Bezier curves. Each call to <b>quadraticVertex()</b> defines the position of one control points and one anchor point of a Bezier curve, adding a new segment to a line or shape. The first time <b>quadraticVertex()</b> is used within a <b>beginShape()</b> call, it must be prefaced with a call to <b>vertex()</b> to set the first anchor point. This function must be used between <b>beginShape()</b> and <b>endShape()</b> and only when there is no MODE parameter specified to <b>beginShape()</b>. Using the 3D version requires rendering with P3D (see the Environment reference for more information).
"
syntax: "quadraticVertex(<c>cx</c>, <c>cy</c>, <c>x3</c>, <c>y3</c>)\nquadraticVertex(<c>cx</c>, <c>cy</c>, <c>cz</c>, <c>x3</c>, <c>y3</c>, <c>z3</c>)"
parameters:
  - label: 'cx'
    description: "float: the x-coordinate of the control point"
  - label: 'cy'
    description: "float: the y-coordinate of the control point"
  - label: 'x3'
    description: "float: the x-coordinate of the anchor point"
  - label: 'y3'
    description: "float: the x-coordinate of the anchor point"
  - label: 'y3'
    description: "float: the y-coordinate of the anchor point"
  - label: 'cz'
    description: "float: the z-coordinate of the control point"
  - label: 'z3'
    description: "float: the z-coordinate of the anchor point"
related:
  - curveVertex
  - vertex
  - bezierVertex
  - bezier
