category: Data
subcategory: String Methods
description: "
Returns true if the string begins with the specified substring, and false
otherwise.
"
syntax: "a.startswith(<c>sub</c>)"
parameters:
  - label: 'sub'
    description: "substring to search for"
related:
  - string
  - string_formatting
  - string_find
  - string_strip
  - string_join
  - string_replace
