category: Structure
subcategory: 
description: "
The <b>super()</b> function allows you to call a method defined in a parent
class. Invoke the function with two parameters: the name of the class the
method is defined in, and <b>self</b>. <a
href=\"https://docs.python.org/2/library/functions.html#super\">See the
official Python documentation</a> for more details.

"
syntax: "super(<c>class</c>, self)"
parameters:
  - label: 'class'
    description: "The class in which the method is defined"
related:
  - class
