category: Control
subcategory: Logical Operators
description: "
Inverts the Boolean value of an expression. Returns <b>True</b> if the expression is <b>False</b> and returns <b>False</b> if the expression is <b>True</b>. If the expression <b>(a>b)</b> evaluates to True, then <b>not(a>b)</b> evaluates to False. 
"
syntax: "not <c>expression</c>"
parameters:
  - label: 'expression'
    description: "any valid expression"
related:
  - logicalOR
  - logicalAND
  - if
