category: Math
subcategory: Calculation
description: "
Calculates a number between two numbers at a specific increment. The <b>amt</b> parameter is the amount to interpolate between the two values where 0.0 equal to the first point, 0.1 is very near the first point, 0.5 is half-way in between, etc. The lerp function is convenient for creating motion along a straight path and for drawing dotted lines.
"
syntax: "lerp(<c>start</c>, <c>stop</c>, <c>amt</c>)"
parameters:
  - label: 'start'
    description: "float: first value"
  - label: 'stop'
    description: "float: second value"
  - label: 'amt'
    description: "float: float between 0.0 and 1.0"
related:
  - curvePoint
  - bezierPoint
  - PVector_lerp
  - lerpColor
