category: Typography
subcategory: Attributes
description: "
Sets the current alignment for drawing text. The parameters LEFT, CENTER, and RIGHT set the display characteristics of the letters in relation to the values for the <b>x</b> and <b>y</b> parameters of the <b>text()</b> function.
<br/> <br/>
An optional second parameter can be used to vertically align the text. BASELINE is the default, and the vertical alignment will be reset to BASELINE if the second parameter is not used. The TOP and CENTER parameters are straightforward. The BOTTOM parameter offsets the line based on the current <b>textDescent()</b>. For multiple lines, the final line will be aligned to the bottom, with the previous lines appearing above it.
<br/> <br/>
When using <b>text()</b> with width and height parameters, BASELINE is ignored, and treated as TOP. (Otherwise, text would by default draw outside the box, since BASELINE is the default setting. BASELINE is not a useful drawing mode for text drawn in a rectangle.)
<br/> <br/>
The vertical alignment is based on the value of <b>textAscent()</b>, which many fonts do not specify correctly. It may be necessary to use a hack and offset by a few pixels by hand so that the offset looks correct. To do this as less of a hack, use some percentage of <b>textAscent()</b> or <b>textDescent()</b> so that the hack works even if you change the size of the font.
"
syntax: "	textAlign(mode)\n	textAlign(modeX, modeY)"
parameters:
  - label: 'mode'
    description: "int: either LEFT, CENTER or RIGHT"
  - label: 'modeX'
    description: "int: either LEFT, CENTER or RIGHT. Horizontally align the text."
  - label: 'modeY'
    description: "int: either TOP, CENTER, BOTTOM or BASELINE. Vertically align the text."
related:
  - loadFont
  - PFont
  - text
