category: Input
subcategory: Time & Date
description: "
Processing communicates with the clock on your computer. The <b>year()</b> function returns the current year as an integer (2003, 2004, 2005, etc).
"
syntax: "	year()"
related:
  - millis
  - second
  - minute
  - hour
  - day
  - month
