category: XMLElement
subcategory: Method
description: "
Returns all of the element's children as an array of XML objects. When the <b>name</b> parameter is specified, then it will return all children that match that name or path. The path is a series of elements and sub-elements, separated by slashes.
"
syntax: ".getChildren()\n.getChildren(<c>name</c>)"
parameters:
  - label: 'name'
    description: "String: element name or path/to/element"
