category: Control
subcategory: Iteration
description: "
Controls a sequence of repetitions. The <b>while</b> structure executes a series of statements continuously while the <b>expression</b> is <b>True</b>. The expression must be updated during the repetitions or the program will never \"break out\" of <b>while</b>.
<br/> <br/>
This function can be dangerous because the code inside the <b>while</b> loop will not finish until the expression inside <b>while</b> becomes False. It will lock out all other code from running (e.g., mouse and keyboard events will not be updated). Be careful &mdash; if used incorrectly, this can lock up your code (and sometimes even the Processing environment itself).
"
syntax: "while <c>expression</c>: \n    <c>statements</c>"
parameters:
  - label: 'expression'
    description: "a valid expression"
  - label: 'statements'
    description: "one or more statements"
related:
  - for
