category: Structure
subcategory: 
description: "
Executes the code within <b>draw()</b> one time. This functions allows the program to update the display window only when necessary, for example when an event registered by <b>mousePressed()</b> or <b>keyPressed()</b> occurs. 
<br/><br/>
In structuring a program, it only makes sense to call redraw() within events such as <b>mousePressed()</b>. This is because <b>redraw()</b> does not run <b>draw()</b> immediately (it only sets a flag that indicates an update is needed). 
<br/><br/>
The <b>redraw()</b> function does not work properly when called inside <b>draw()</b>. To enable/disable animations, use <b>loop()</b> and <b>noLoop()</b>.
"
syntax: "edraw("
related:
  - draw
  - loop
  - noLoop
  - frameRate
