category: Table
subcategory: Method
description: "
Stores a float value in the <b>Table</b>'s specified row and column. The row is specified by its ID, while the column may be specified by either its ID or title.
"
syntax: ".setFloat(row, column, value)\n.setFloat(row, columnName, value)"
parameters:
  - label: 'row'
    description: "int: ID number of the target row"
  - label: 'column'
    description: "int: ID number of the target column"
  - label: 'value'
    description: "float: value to assign"
  - label: 'columnName'
    description: "String: title of the target column"
related:
  - XML_setInt
  - XML_setString
  - XML_getInt
  - XML_getFloat
  - XML_getString
  - Table_getStringColumn
