category: Shape
subcategory: Vertex
description: "
Use the <b>beginContour()</b> and <b>endContour()</b> function to create negative shapes within shapes. For instance, the center of the letter 'O'. <b>beginContour()</b> begins recording vertices for the shape and <b>endContour()</b> stops recording. These functions can only be within a <b>beginShape()</b>/<b>endShape()</b> pair and they only work with the P2D and P3D renderers. <br />
<br/>
Transformations such as <b>translate()</b>, <b>rotate()</b>, and <b>scale()</b> do not work within a <b>beginContour()</b>/<b>endContour()</b> pair. It is also not possible to use other shapes, such as <b>ellipse()</b> or <b>rect()</b> within.
"
syntax: "endContour()\n"
