category: Input
subcategory: Keyboard
description: "
The <b>keyTyped()</b> function is called once every time a key is pressed, but action keys such as Ctrl, Shift, and Alt are ignored. Because of how operating systems handle key repeats, holding down a key will cause multiple calls to <b>keyTyped()</b>, the rate is set by the operating system and how each computer is configured. 
<br/><br/>
Mouse and keyboard events only work when a program has <b>draw()</b>. Without <b>draw()</b>, the code is only run once and then stops listening for events.
"
syntax: "keyTyped()\nkeyTyped(event)"
parameters:
  - label: 'event'
    description: "MouseEvent: the MouseEvent"
related:
  - keyPressed_var
  - key
  - keyCode
  - keyReleased
