category: Shape
subcategory: Vertex
description: "
All shapes are constructed by connecting a series of vertices. <b>vertex()</b> is used to specify the vertex coordinates for points, lines, triangles, quads, and polygons. It is used exclusively within the <b>beginShape()</b> and <b>endShape()</b> functions.
<br/><br/>
Drawing a vertex in 3D using the <b>z</b> parameter requires the P3D parameter in combination with size, as shown in the above example.
<br/><br/>
This function is also used to map a texture onto geometry. The <b>texture()</b> function declares the texture to apply to the geometry and the <b>u</b> and <b>v</b> coordinates set define the mapping of this texture to the form. By default, the coordinates used for <b>u</b> and <b>v</b> are specified in relation to the image's size in pixels, but this relation can be changed with <b>textureMode()</b>.
"
syntax: ""
related:
  - PShape_beginShape
  - PShape_endShape
  - bezierVertex
  - quadraticVertex
  - curveVertex
  - texture
