category: Structure
subcategory: 
description: "
Range() generates lists containing arithmetic progressions. It is useful when you need to iterate over a sequence of numbers. The end point is never part of the generated list, i.e. the list generate by range(5) will not include 5. 
It is possible to let range start at another number, or to specify another increment.
"
syntax: "range(<c>end</c>)\nrange(<c>start</c>, <c>end</c>)\nrange(<c>start</c>, <c>end</c>, <c>increment</c>)"
parameters:
  - label: 'start'
    description: " start point of the generated list "
  - label: 'end'
    description: " end point of the generated list "
  - label: 'increment'
    description: " value to increment by  "
