category: Data
subcategory: Composite
description: "
A <b>TableRow</b> object represents a single row of data values, stored in columns, from a table.
"
syntax: ""
related:
  - Table
  - Table_addRow
  - Table_removeRow
  - Table_clearRows
  - Table_getRow
  - Table_rows
