category: PShape
subcategory: Method
description: "
Specifies an amount to displace the shape. The <b>x</b> parameter specifies left/right translation, the <b>y</b> parameter specifies up/down translation, and the <b>z</b> parameter specifies translations toward/away from the screen. Subsequent calls to the method accumulates the effect. For example, calling <b>translate(50, 0)</b> and then <b>translate(20, 0)</b> is the same as <b>translate(70, 0)</b>. This transformation is applied directly to the shape, it's not refreshed each time <b>draw()</b> is run. 
<br /><br />
Using this method with the <b>z</b> parameter requires using the P3D parameter in combination with size. 
"
syntax: "<c>sh</c>.translate(<c>x</c>, <c>y</c>)\n<c>sh</c>.translate(<c>x</c>, <c>y</c>, <c>z</c>)"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
  - label: 'x'
    description: "float: left/right translation"
  - label: 'y'
    description: "float: up/down translation"
  - label: 'z'
    description: "float: forward/backward translation"
related:
  - popMatrix
  - pushMatrix
  - rotate
  - rotateX
  - rotateY
  - rotateZ
  - scale
