category: Shape
subcategory: Attributes
description: "
Draws all geometry with jagged (aliased) edges.  Note that <b>smooth()</b> is active by default, so it is necessary to call <b>noSmooth()</b> to disable smoothing of geometry, images, and fonts.
"
syntax: "noSmooth()"
related:
  - smooth
