category: XMLElement
subcategory: Method
description: "
Returns an attribute value of the element as an int. If the <b>defaultValue</b> parameter is specified and the attribute doesn't exist, then <b>defaultValue</b> is returned. If no <b>defaultValue</b> is specified and the attribute doesn't exist, the value 0 is returned.
"
syntax: ".getInt(<c>name</c>)\n.getInt(<c>name</c>, <c>defaultValue</c>)"
parameters:
  - label: 'name'
    description: "String: the non-null full name of the attribute"
  - label: 'defaultValue'
    description: "int: the default value of the attribute"
