category: Data
subcategory: Conversion
description: "
Converts a color to a String containing the equivalent hexadecimal notation. For example, the color value produced by <b>color(0, 102, 153)</b> will convert to the String value \"FF006699\". This function can help make your geeky debugging sessions much happier.<br/>
<br/>
Note that the maximum number of digits is 8, because an <b>int</b> value can only represent up to 32 bits. Specifying more than 8 digits will not increase the length of the string further.
"
syntax: ""
related:
  - unhex
  - binary
  - unbinary
