category: Math
subcategory: Calculation
description: "
Calculates the square root of a number. The square root of a number is always positive, even though there may be a valid negative root. The square root <b>s</b> of number <b>a</b> is such that <b>s*s = a</b>. It is the opposite of squaring.
"
syntax: "	sqrt(n)"
parameters:
  - label: 'n'
    description: "value whose root is to be calculated"
related:
  - sqrt
