category: Lights, Camera
subcategory: Lights
description: "
Sets the falloff rates for point lights, spot lights, and ambient lights. Like <b>fill()</b>, it affects only the elements which are created after it in the code. The default value is <b>lightFalloff(1.0, 0.0, 0.0)</b>, and the parameters are used to calculate the falloff with the following equation:<br/>
<br/>
d = distance from light position to vertex position<br/>
falloff = 1 / (CONSTANT + d * LINEAR + (d*d) * QUADRATIC)<br/>
<br/>
Thinking about an ambient light with a falloff can be tricky. If you want a region of your scene to be lit ambiently with one color and another region to be lit ambiently with another color, you could use an ambient light with location and falloff. You can think of it as a point light that doesn't care which direction a surface is facing.
"
syntax: "lightFalloff(<c>constant</c>, <c>linear</c>, <c>quadratic</c>)"
parameters:
  - label: 'constant'
    description: "float: constant value or determining falloff"
  - label: 'linear'
    description: "float: linear value for determining falloff"
  - label: 'quadratic'
    description: "float: quadratic value for determining falloff"
related:
  - lights
  - ambientLight
  - pointLight
  - spotLight
  - lightSpecular
