category: Math
subcategory: Random
description: "
Returns the Perlin noise value at specified coordinates. Perlin noise is a random sequence generator producing a more natural, harmonic succession of numbers than that of the standard <b>random()</b> function. It was invented by Ken Perlin in the 1980s and has been used in graphical applications to generate procedural textures, shapes, terrains, and other seemingly organic forms.<br/>
<br/>
In contrast to the <b>random()</b> function, Perlin noise is defined in an infinite n-dimensional space, in which each pair of coordinates corresponds to a fixed semi-random value (fixed only for the lifespan of the program). The resulting value will always be between 0.0 and 1.0. Processing can compute 1D, 2D and 3D noise, depending on the number of coordinates given. The noise value can be animated by moving through the noise space, as demonstrated in the first example above. The 2nd and 3rd dimensions can also be interpreted as time.<br/>
<br/>
The actual noise structure is similar to that of an audio signal, in respect to the function's use of frequencies. Similar to the concept of harmonics in physics, Perlin noise is computed over several octaves which are added together for the final result.<br/>
<br/>
Another way to adjust the character of the resulting sequence is the scale of the input coordinates. As the function works within an infinite space, the value of the coordinates doesn't matter as such; only the <em>distance</em> between successive coordinates is important (such as when using <b>noise()</b> within a loop). As a general rule, the smaller the difference between coordinates, the smoother the resulting noise sequence. Steps of 0.005-0.03 work best for most applications, but this will differ depending on use.
"
syntax: "noise(<c>x</c>)\nnoise(<c>x</c>, <c>y</c>)\nnoise(<c>x</c>, <c>y</c>, <c>z</c>)"
parameters:
  - label: 'x'
    description: "float: x-coordinate in noise space"
  - label: 'y'
    description: "float: y-coordinate in noise space"
  - label: 'z'
    description: "float: z-coordinate in noise space"
related:
  - noiseSeed
  - noiseDetail
  - random
