category: Shape
subcategory: 3D Primitives
description: "
Controls the detail used to render a sphere by adjusting the number of vertices of the sphere mesh. The default resolution is 30, which creates a fairly detailed sphere definition with vertices every 360/30 = 12 degrees. If you're going to render a great number of spheres per frame, it is advised to reduce the level of detail using this function. The setting stays active until <b>sphereDetail()</b> is called again with a new parameter and so should <i>not</i> be called prior to every <b>sphere()</b> statement, unless you wish to render spheres with different settings, e.g. using less detail for smaller spheres or ones further away from the camera. To control the detail of the horizontal and vertical resolution independently, use the version of the functions with two parameters.
"
syntax: "sphereDetail(<c>res</c>)\nsphereDetail(<c>ures</c>, <c>vres</c>)"
parameters:
  - label: 'res'
    description: "int: number of segments (minimum 3) used per full circle revolution"
  - label: 'ures'
    description: "int: number of segments used longitudinally per full circle revolution"
  - label: 'vres'
    description: "int: number of segments used latitudinally from top to bottom"
related:
  - sphere
