category: XMLElement
subcategory: Method
description: "
Sets the content of an element's attribute as an int.  A String specifies the attribute name, while the int specifies the new content.
"
syntax: ".setInt(name, value)\n"
