category: Structure
subcategory: 
description: "

Returns the length of its parameter. The meaning of \"length\" varies from one
type to the next. For strings, <b>len()</b> returns the number of
characters in the string. For dictionaries, it returns the number of keys
in the dictionary. For other sequences and collections (like
lists, tuples and sets), it returns the number of items in the sequence or
collection.

"
syntax: "len(<c>a</c>)"
parameters:
  - label: 'a'
    description: "the object (usually a string, list or dictionary) whose length you want to determine"
related:
  - list
  - string
  - dictionary
