category: Shape
subcategory: 3D Primitives
description: "
A box is an extruded rectangle. A box with equal dimensions on all sides is a cube.
"
syntax: "box(<c>size</c>)\nbox(<c>w</c>, <c>h</c>, <c>d</c>)"
parameters:
  - label: 'size'
    description: "float: dimension of the box in all dimensions (creates a cube)"
  - label: 'w'
    description: "float: dimension of the box in the x-dimension"
  - label: 'h'
    description: "float: dimension of the box in the y-dimension"
  - label: 'd'
    description: "float: dimension of the box in the z-dimension"
related:
  - sphere
