category: Lights, Camera
subcategory: Lights
description: "
Sets the current normal vector. Used for drawing three dimensional shapes and surfaces, <b>normal()</b> specifies a vector perpendicular to a shape's surface which, in turn, determines how lighting affects it. Processing attempts to automatically assign normals to shapes, but since that's imperfect, this is a better option when you want more control. This function is identical to <b>glNormal3f()</b> in OpenGL.
"
syntax: "normal(<c>nx</c>, <c>ny</c>, <c>nz</c>)"
parameters:
  - label: 'nx'
    description: "float: x direction"
  - label: 'ny'
    description: "float: y direction"
  - label: 'nz'
    description: "float: z direction"
related:
  - PShape_beginShape
  - PShape_endShape
  - lights
