category: Math
subcategory: Operators
description: "
Multiplies the values of the two parameters. Multiplication is equivalent to a sequence of addition. For example 5 * 4 is equivalent to 5 + 5 + 5 + 5.
"
syntax: "<c>value1</c> * <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int, float, byte, or char"
  - label: 'value2'
    description: "int, float, byte, or char"
related:
  - addition
  - divide
