category: Input
subcategory: Time & Date
description: "
Returns the number of milliseconds (thousandths of a second) since starting the program as an integer. This information is often used for timing events and animation sequences. 
"
syntax: "millis()"
related:
  - second
  - minute
  - hour
  - day
  - month
  - year
