category: Transform
subcategory: 
description: "
Rotates a shape the amount specified by the <b>angle</b> parameter. Angles must be specified in radians (values from <b>0</b> to <b>TWO_PI</b>), or they can be converted from degrees to radians with the <b>radians()</b> function. 
<br/> <br/>
Objects are always rotated around their relative position to the origin, and positive numbers rotate objects in a clockwise direction. Transformations apply to everything that happens afterward, and subsequent calls to the function compound the effect. For example, calling <b>rotate(HALF_PI)</b> once and then calling <b>rotate(HALF_PI)</b> a second time is the same as a single <b>rotate(PI)</b>. All tranformations are reset when <b>draw()</b> begins again. 
<br/> <br/>
Technically, <b>rotate()</b> multiplies the current transformation matrix by a rotation matrix. This function can be further controlled by <b>pushMatrix()</b> and <b>popMatrix()</b>.
"
syntax: "rotate(<c>angle</c>)\nrotate(<c>angle</c>, x, y, z)"
parameters:
  - label: 'angle'
    description: "float: angle of rotation specified in radians"
related:
  - popMatrix
  - pushMatrix
  - rotateX
  - rotateY
  - rotateZ
  - scale
  - radians
