category: Lights, Camera
subcategory: Material Properties
description: "
Sets the specular color of the materials used for shapes drawn to the screen, which sets the color of highlights. Specular refers to light which bounces off a surface in a preferred direction (rather than bouncing in all directions like a diffuse light). Used in combination with <b>emissive()</b>, <b>ambient()</b>, and <b>shininess()</b> in setting the material properties of shapes.
"
syntax: "specular(<c>rgb</c>)\nspecular(<c>gray</c>)\nspecular(<c>v1</c>, <c>v2</c>, <c>v3</c>)"
parameters:
  - label: 'rgb'
    description: "int: color to set"
  - label: 'v1'
    description: "float: red or hue value (depending on current color mode)"
  - label: 'v2'
    description: "float: green or saturation value (depending on current color mode)"
  - label: 'v3'
    description: "float: blue or brightness value (depending on current color mode)"
related:
  - lightSpecular
  - ambient
  - emissive
  - shininess
