category: PImage
subcategory: Method
description: "
Resize the image to a new width and height. To make the image scale proportionally, use 0 as the value for the <b>wide</b> or <b>high</b> parameter. For instance, to make the width of an image 150 pixels, and change the height using the same proportion, use resize(150, 0).<br />
<br />
Even though a PGraphics is technically a PImage, it is not possible to rescale the image data found in a PGraphics. (It's simply not possible to do this consistently across renderers: technically infeasible with P3D, or what would it even do with PDF?) If you want to resize PGraphics content, first get a copy of its image data using the <b>get()</b> method, and call <b>resize()</b> on the PImage that is returned.
"
syntax: "\n<c>pimg</c>.resize(<c>w</c>,<c>h</c>)"
parameters:
  - label: 'pimg'
    description: "PImage: any object of type PImage"
  - label: 'w'
    description: "int: the resized image width"
  - label: 'h'
    description: "int: the resized image height"
related:
  - PVector_get
