category: Math
subcategory: Calculation
description: "
Normalizes a number from another range into a value between 0 and 1. Identical to <b>map(value, low, high, 0, 1)</b>.<br/>
<br/>
Numbers outside of the range are not clamped to 0 and 1, because out-of-range values are often intentional and useful.  (See the second example above.)
"
syntax: "norm(<c>value</c>, <c>start</c>, <c>stop</c>)"
parameters:
  - label: 'value'
    description: "float: the incoming value to be converted"
  - label: 'start'
    description: "float: lower bound of the value's current range"
  - label: 'stop'
    description: "float: upper bound of the value's current range"
related:
  - map
  - PVector_lerp
