category: Structure
subcategory: 
description: "
Remove an item from a list given its index, or a key/value pair from a dictionary. The <b>del</b> keyword can also delete an entire variable.
"
syntax: "del <c>a</c>"
parameters:
  - label: 'a'
    description: "list or dictionary to delete from, or variable to delete"
  - label: 'i'
    description: "index of list member or key of key/value pair to delete"
