category: Structure
subcategory: 
description: " None is often used to represent the absences of a value. Such as
	when default arguments are not passed to a function. 
"
syntax: "x = None "
parameters:
  - label: ''
    description: ""
related:
  - True
  - False
