category: Input
subcategory: Mouse
description: "
The <b>mouseDragged()</b> function is called once every time the mouse moves while a mouse button is pressed. (If a button <i>is not</i> being pressed, <b>mouseMoved()</b> is called instead.)
<br/><br/>
Mouse and keyboard events only work when a program has <b>draw()</b>. Without <b>draw()</b>, the code is only run once and then stops listening for events.
"
syntax: "mouseDragged()\nmouseDragged(event)"
related:
  - mouseX
  - mouseY
  - pmouseX
  - pmouseY
  - mousePressed_var
  - mousePressed
  - mouseReleased
  - mouseClicked
  - mouseMoved
  - mouseButton
  - mouseWheel
