category: Transform
subcategory: 
description: "
Increases or decreases the size of a shape by expanding and contracting vertices. Objects always scale from their relative origin to the coordinate system. Scale values are specified as decimal percentages. For example, the function call <b>scale(2.0)</b> increases the dimension of a shape by 200%.<br/>
<br/>
Transformations apply to everything that happens after and subsequent calls to the function multiply the effect. For example, calling <b>scale(2.0)</b> and then <b>scale(1.5)</b> is the same as <b>scale(3.0)</b>. If <b>scale()</b> is called within <b>draw()</b>, the transformation is reset when the loop begins again. Using this function with the <b>z</b> parameter requires using P3D as a parameter for <b>size()</b>, as shown in the third example above. This function can be further controlled with <b>pushMatrix()</b> and <b>popMatrix()</b>.
"
syntax: "scale(<c>s</c>)\nscale(<c>x</c>, <c>y</c>)\nscale(<c>x</c>, <c>y</c>, <c>z</c>)"
parameters:
  - label: 's'
    description: "float: percentage to scale the object"
  - label: 'x'
    description: "float: percentage to scale the object in the x-axis"
  - label: 'y'
    description: "float: percentage to scale the object in the y-axis"
  - label: 'z'
    description: "float: percentage to scale the object in the z-axis"
related:
  - pushMatrix
  - popMatrix
  - translate
  - rotate
  - rotateX
  - rotateY
  - rotateZ
