category: Environment
subcategory: 
description: "
System variable that stores the height of the display window. This value is set by the second parameter of the <b>size()</b> function. For example, the function call <b>size(320, 240)</b> sets the <b>height</b> variable to the value 240. The value of <b>height</b> defaults to 100 if <b>size()</b> is not used in a program.
"
syntax: "	rect(40, 0, 20, height)"
related:
  - width
  - size
