category: PVector
subcategory: Method
description: "
Return a representation of this vector as a float array. This is only for temporary use. If used in any other fashion, the contents should be copied by using the <b>PVector.get()</b> method to copy into your own array.
"
syntax: ".array()\n"
