category: Data
subcategory: List Functions
description: "
Return an iterator that will produce the elements of the given list (or other
iterable) reverse order. This function differs from the list object's
<b>reverse()</b> method in that it does not modify the list in-place. It can
also take as a parameter any iterable (e.g., a string, dictionary, or tuple),
not just a list (as shown in the string example above).<br/><br/>

Because <b>reversed()</b> returns an iterator, you normally need to iterate
over its result in a <b>for</b> loop (as shown in the first example above).
You can use the <b>list()</b> function to get the entire reversed iterable in
one go.

"
syntax: "	reversed(<c>x</c>)"
parameters:
  - label: 'x'
    description: "The iterable (list, string, dictionary, etc.) to reverse"
related:
  - list_reverse
  - list_sort
  - list
  - sorted
