category: XMLElement
subcategory: Method
description: "
Returns the content of an element as an int. If there is no such content, either <b>null</b> or the provided default value is returned.
"
syntax: ".getIntContent()\n.getIntContent(<c>defaultValue</c>)"
parameters:
  - label: 'defaultValue'
    description: "int: the default value of the attribute"
related:
  - XML_getContent
  - XML_getFloatContent
