category: Environment
subcategory: 
description: "
Confirms if a Processing program is \"focused,\" meaning that it is active and will accept mouse or keyboard input. This variable is <tt>True</tt> if it is focused and <tt>False</tt> if not.
"
syntax: "	if (focused):\n	    statements"
