category: Math
subcategory: Operators
description: "
Combines addition with assignment for numbers, concatenation with assignment for strings, and list appending with assignment for lists. The expression <b>a += b</b> is equivalent to <b>a = a + b</b>. 
"
syntax: "<c>value1</c> += <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int, float, list,  string"
  - label: 'value2'
    description: "any value the same datatype as value1"
related:
  - assign
  - addition
  - subtractassign
