category: Math
subcategory: Operators
description: "
Divides the value of the first parameter by the value of the second parameter. The answer to the equation 20 / 4 is 5. The number 20 is the sum of four occurences of the number 5. As an equation we see that 5 + 5 + 5 + 5 = 20.
"
syntax: "<c>value1</c> / <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int or float"
  - label: 'value2'
    description: "int or float, but not zero (it is not possible  divide by zero)"
related:
  - multiply
  - modulo
