category: Data
subcategory: String Functions
description: "
Utility function for formatting numbers into strings. There are two versions: one for formatting floats, and one for formatting ints. The values for the <b>digits</b>, <b>left</b>, and <b>right</b> parameters should always be positive integers.<br /><br />As shown in the above example, <b>nf()</b> is used to add zeros to the left and/or right of a number. This is typically for aligning a list of numbers. To <em>remove</em> digits from a floating-point number, use the <b>int()</b>, <b>ceil()</b>, <b>floor()</b>, or <b>round()</b> functions.  
"
syntax: "nf(<c>num</c>, <c>digits</c>)\nnf(<c>num</c>, <c>left</c>, <c>right</c>)"
parameters:
  - label: 'num'
    description: "the number(s) to format"
  - label: 'digits'
    description: "int: number of digits to pad with zero"
  - label: 'left'
    description: "int: number of digits to the left of the decimal point"
  - label: 'right'
    description: "int: number of digits to the right of the decimal point"
related:
  - nfs
  - nfp
  - nfc
