category: Data
subcategory: String Functions
description: "
Utility function for formatting numbers into strings and placing appropriate commas to mark units of 1000. There are two versions: one for formatting ints, and one for formatting an array of ints. The value for the <b>right</b> parameter should always be a positive integer.
<br/> <br/>
For a non-US locale, this will insert periods instead of commas, or whatever is apprioriate for that region.
"
syntax: "nfc(<c>num</c>)\nnfc(<c>num</c>, <c>right</c>)"
parameters:
  - label: 'num'
    description: "the number(s) to format"
  - label: 'right'
    description: "int: number of digits to the right of the decimal point"
related:
  - nf
  - nfp
