category: Rendering
subcategory: 
description: "
Blends the pixels in the display window according to the defined mode. There is a choice of the following modes to blend the source pixels (A) with the ones of pixels already in the display window (B):<br />
<br />
BLEND - linear interpolation of colours: C = A*factor + B. This is the default blending mode.<br />
<br />
ADD - additive blending with white clip: C = min(A*factor + B, 255)<br />
<br />
SUBTRACT - subtractive blending with black clip: C = max(B - A*factor, 0)<br />
<br />
DARKEST - only the darkest colour succeeds: C = min(A*factor, B)<br />
<br />
LIGHTEST - only the lightest colour succeeds: C = max(A*factor, B)<br />
<br />
DIFFERENCE - subtract colors from underlying image.<br />
<br />
EXCLUSION - similar to DIFFERENCE, but less extreme.<br />
<br />
MULTIPLY - multiply the colors, result will always be darker.<br />
<br />
SCREEN - opposite multiply, uses inverse values of the colors.<br />
<br />
REPLACE - the pixels entirely replace the others and don't utilize alpha (transparency) values<br />
<br />
For Processing 2.0, we recommend using <b>blendMode()</b> and not the previous <b>blend()</b> function. However, unlike <b>blend()</b>, the <b>blendMode()</b> function does not support the following: HARD_LIGHT, SOFT_LIGHT, OVERLAY, DODGE, BURN. On older hardware, the LIGHTEST, DARKEST, and DIFFERENCE modes might not be available as well. 
"
syntax: "blendMode(<c>mode</c>)"
parameters:
  - label: 'mode'
    description: "int: either BLEND, SUBTRACT, DARKEST, LIGHTEST, DIFFERENCE, EXCLUSION, MULTIPLY, SCREEN or REPLACE"
