category: Structure
subcategory: 
description: "
	Grouping and containing expressions and parameters. Parentheses have multiple functions relating to functions and structures. They are used to contain a list of parameters passed to functions and control structures and they are used to group expressions to control the order of execution. Some functions have no parameters and in this case, the space between parentheses is blank.<br/><br/>

	Parentheses are also used to write tuple literals. <ref target=\"tuple.xml\">See the documentation on tuples</ref> for more information.
"
syntax: "<c>function</c>()\n<c>function</c>(<c>p1</c>, ..., <c>pN</c>)\n(<c>expression</c>)\n(<c>tuple_item1, ..., tuple_itemN</c>)"
parameters:
  - label: 'function'
    description: "any function"
  - label: 'p1, ..., pN'
    description: "list of parameters specific to the function"
  - label: 'expression'
    description: "any valid expression"
  - label: 'tuple_item1, ..., tuple_itemN'
    description: "a series of comma-separated expressions (to create a tuple)"
related:
  - comma
  - tuple
