category: Data
subcategory: Primitive
description: "
Datatype for integers, numbers without a decimal point. Integers can be as large as 9,223,372,036,854,775,807 and as low as -9,223,372,036,854,775,808. They are stored as 32 bits of information.  
"
syntax: "<c>var</c> = <c>value</c>"
parameters:
  - label: 'var'
    description: "variable name referencing the value"
  - label: 'value'
    description: "any integer value"
related:
  - float
