category: Constants
subcategory: 
description: "
QUARTER_PI is a mathematical constant with the value 0.7853982. It is one quarter the ratio of the circumference of a circle to its diameter. It is useful in combination with the trigonometric functions <b>sin()</b> and <b>cos()</b>. 
"
syntax: ""
related:
  - PI
  - TWO_PI
  - TAU
  - HALF_PI
