category: Input
subcategory: Files
description: "
Reads the contents of a file or URL and creates an XML object with its values. If a file is specified, it must be located in the sketch's \"data\" folder. The filename parameter can also be a URL to a file found online.<br/>
<br/>
All files loaded and saved by the Processing API use UTF-8 encoding. If you need to load an XML file that's not in UTF-8 format, see the <a href=\"http://processing.org/reference/javadoc/core/processing/data/XML.html\">developer's reference</a> for the XML object.
"
syntax: "loadXML(<c>filename</c>)"
parameters:
  - label: 'filename'
    description: "String: name of a file in the data folder or a URL."
related:
  - XML
  - parseXML
  - saveXML
  - loadBytes
  - loadStrings
  - loadTable
