category: Color
subcategory: Setting
description: "
The <b>background()</b> function sets the color used for the background of the Processing window. The default background is light gray. This function is typically used within <b>draw()</b> to clear the display window at the beginning of each frame, but it can be used inside <b>setup()</b> to set the background on the first frame of animation or if the backgound need only be set once.
<br/> <br/>
An image can also be used as the background for a sketch, although the image's width and height must match that of the sketch window. Images used with <b>background()</b> will ignore the current <b>tint()</b> setting. To resize an image to the size of the sketch window, use image.resize(width, height).
<br/> <br/>
It is not possible to use the transparency <b>alpha</b> parameter with background colors on the main drawing surface. It can only be used along with a <b>PGraphics</b> object and <b>createGraphics()</b>.
"
syntax: "background(<c>rgb</c>)\nbackground(<c>rgb</c>, <c>alpha</c>)\nbackground(<c>gray</c>)\nbackground(<c>gray</c>, <c>alpha</c>)\nbackground(<c>v1</c>, <c>v2</c>, <c>v3</c>)\nbackground(<c>v1</c>, <c>v2</c>, <c>v3</c>, <c>alpha</c>)\nbackground(<c>image</c>)"
parameters:
  - label: 'rgb'
    description: "int: any value of the color datatype"
  - label: 'alpha'
    description: "float: opacity of the background"
  - label: 'gray'
    description: "float: specifies a value between white and black"
  - label: 'v1'
    description: "float: red or hue value (depending on the current color mode)"
  - label: 'v2'
    description: "float: green or saturation value (depending on the current color mode)"
  - label: 'v3'
    description: "float: blue or brightness value (depending on the current color mode)"
  - label: 'image'
    description: "PImage: PImage to set as background (must be same size as the sketch window)"
related:
  - stroke
  - fill
  - tint
  - colorMode
