category: Image
subcategory: Pixels
description: "
Loads the pixel data for the display window into the <b>pixels</b> array. This function must always be called before reading from or writing to <b>pixels</b>.<br/>
<br/>
Certain renderers may or may not seem to require <b>loadPixels()</b> or <b>updatePixels()</b>. However, the rule is that any time you want to manipulate the <b>pixels</b> array, you must first call <b>loadPixels()</b>, and after changes have been made, call <b>updatePixels()</b>. Even if the renderer may not seem to use this function in the current Processing release, this will always be subject to change.
"
syntax: "oadPixels("
related:
  - pixels
  - updatePixels
