category: Lights, Camera
subcategory: Lights
description: "
Sets the specular color for lights. Like <b>fill()</b>, it affects only the elements which are created after it in the code. Specular refers to light which bounces off a surface in a preferred direction (rather than bouncing in all directions like a diffuse light) and is used for creating highlights. The specular quality of a light interacts with the specular material qualities set through the <b>specular()</b> and <b>shininess()</b> functions.
"
syntax: "lightSpecular(<c>v1</c>, <c>v2</c>, <c>v3</c>)"
parameters:
  - label: 'v1'
    description: "float: red or hue value (depending on current color mode)"
  - label: 'v2'
    description: "float: green or saturation value (depending on current color mode)"
  - label: 'v3'
    description: "float: blue or brightness value (depending on current color mode)"
related:
  - specular
  - lights
  - ambientLight
  - pointLight
  - spotLight
