category: Input
subcategory: Time & Date
description: "
Processing communicates with the clock on your computer. The <b>day()</b> function returns the current day as a value from 1 - 31.
"
syntax: "day()"
related:
  - millis
  - second
  - minute
  - hour
  - month
  - year
