category: Image
subcategory: Loading & Displaying
description: "
This function loads images on a separate thread so that your sketch doesn't freeze while images load during <b>setup()</b>. While the image is loading, its width and height will be 0. If an error occurs while loading the image, its width and height will be set to -1. You'll know when the image has loaded properly because its <b>width</b> and <b>height</b> will be greater than 0. Asynchronous image loading (particularly when downloading from a server) can dramatically improve performance.<br />
<br/>
The <b>extension</b> parameter is used to determine the image type in cases where the image filename does not end with a proper extension. Specify the extension as the second parameter to <b>requestImage()</b>.
"
syntax: "requestImage(<c>filename</c>)\nrequestImage(<c>filename</c>, <c>extension</c>)"
parameters:
  - label: 'filename'
    description: "String: name of the file to load, can be .gif, .jpg, .tga, or a handful of other image types depending on your platform"
  - label: 'extension'
    description: "String: the type of image to load, for example \"png\", \"gif\", \"jpg\""
related:
  - PImage
  - loadImage
