category: PShape
subcategory: Method
description: "
Sets the shape to be visible or invisible. This is determined by the value of the <b>visible</b> parameter.<br/>
<br/>
The default visibility of a shape is usually controlled by whatever program created the SVG file. For instance, this parameter is controlled by showing or hiding the shape in the layers palette in Adobe Illustrator.
"
syntax: "c>sh</c>.setVisible(<c>visible</c>"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
  - label: 'visible'
    description: "boolean: \"false\" makes the shape invisible and \"true\" makes it visible"
related:
  - PShape_isVisible
