category: Structure
subcategory: 
description: "
The <b>setup()</b> function is called once when the program starts. It's used to define initial 
enviroment properties such as screen size and background color and to load media such as images
and fonts as the program starts. There can only be one <b>setup()</b> function for each program and 
it shouldn't be called again after its initial execution. Note: Variables declared within 
<b>setup()</b> are not accessible within other functions, including <b>draw()</b>. 
"
syntax: "setup()"
related:
  - size
  - loop
  - noLoop
  - draw
