category: Transform
subcategory: 
description: "
Rotates a shape around the x-axis the amount specified by the <b>angle</b> parameter. Angles should be specified in radians (values from 0 to PI*2) or converted to radians with the <b>radians()</b> function. Objects are always rotated around their relative position to the origin and positive numbers rotate objects in a counterclockwise direction. Transformations apply to everything that happens after and subsequent calls to the function accumulates the effect. For example, calling <b>rotateX(PI/2)</b> and then <b>rotateX(PI/2)</b> is the same as <b>rotateX(PI)</b>. If <b>rotateX()</b> is called within the <b>draw()</b>, the transformation is reset when the loop begins again. This function requires using P3D as a third parameter to <b>size()</b> as shown in the example above. 
"
syntax: "rotateX(<c>angle</c>)"
parameters:
  - label: 'angle'
    description: "float: angle of rotation specified in radians"
related:
  - popMatrix
  - pushMatrix
  - rotate
  - rotateY
  - rotateZ
  - scale
  - translate
