category: Data
subcategory: List Methods
description: "
Return the index in the list of the first item whose value is x. Raises a ValueError exception if there is no such item.
"
syntax: "<c>a</c>.index(<c>x</c>)"
parameters:
  - label: 'a'
    description: "the list to search through"
  - label: 'x'
    description: "the item to search for"
related:
  - list_insert
  - list_pop
  - list_reverse
  - list_append
