category: Color
subcategory: Creating & Reading
description: "
Extracts the blue value from a color, scaled to match current <b>colorMode()</b>. The value is always returned as a float, so be careful not to assign it to an int value.<br />
<br />
The <b>blue()</b> function is easy to use and understand, but it is slower than a technique called bit masking. When working in <b>colorMode(RGB, 255)</b>, you can acheive the same results as <b>blue()</b> but with greater speed by using a bit mask to remove the other color components. For example, the following two lines of code are equivalent means of getting the blue value of the color value <b>c</b>:<br />
<br />
<pre>b1 = blue(c);   # Simpler, but slower to calculate
b2 = c & 0xFF;  # Very fast to calculate</pre>
"
syntax: "blue(<c>rgb</c>)"
parameters:
  - label: 'rgb'
    description: "int: any value of the color datatype"
related:
  - red
  - green
  - alpha
  - hue
  - saturation
  - brightness
  - rightshift
