category: PImage
subcategory: Method
description: "
Changes the color of any pixel or writes an image directly into the display window.<br />
<br />
The <b>x</b> and <b>y</b> parameters specify the pixel to change and the <b>color</b> parameter specifies the color value. The color parameter is affected by the current color mode (the default is RGB values from 0 to 255). When setting an image, the <b>x</b> and <b>y</b> parameters define the coordinates for the upper-left corner of the image, regardless of the current <b>imageMode()</b>.
<br /><br />
Setting the color of a single pixel with <b>set(x, y)</b> is easy, but not as fast as putting the data directly into <b>pixels</b>. The equivalent statement to <b>set(x, y, #000000)</b> using <b>pixels</b> is <b>pixels[y*width+x] = #000000</b>. See the reference for <b>pixels</b> for more information.
"
syntax: "<c>pimg</c>.set(<c>x</c>, <c>y</c>, <c>c</c>)\n<c>pimg</c>.set(<c>x</c>, <c>y</c>, <c>img</c>)"
parameters:
  - label: 'pimg'
    description: "PImage: any object of type PImage"
  - label: 'x'
    description: "int: x-coordinate of the pixel"
  - label: 'y'
    description: "int: y-coordinate of the pixel"
  - label: 'c'
    description: "int: any value of the color datatype"
  - label: 'img'
    description: "PImage: image to copy into the original image"
related:
  - PVector_get
  - pixels
