category: Lights, Camera
subcategory: Camera
description: "
The <b>beginCamera()</b> and <b>endCamera()</b> functions enable advanced customization of the camera space. Please see the reference for <b>beginCamera()</b> for a description of how the functions are used.
"
syntax: "endCamera()"
related:
  - camera
