category: Lights, Camera
subcategory: Camera
description: "
Sets a perspective matrix as defined by the parameters.<br/>
<br/>
A frustum is a geometric form: a pyramid with its top cut off.  With the viewer's eye at the imaginary top of the pyramid, the six planes of the frustum act as clipping planes when rendering a 3D view.  Thus, any form inside the clipping planes is rendered and visible; anything outside those planes is not visible.<br/>
<br/>
Setting the frustum has the effect of changing the <em>perspective</em> with which the scene is rendered.  This can be acheived more simply in many cases by using <strong>perspective()</strong>.<br/>
<br/>
Note that the near value must be greater than zero (as the point of the frustum \"pyramid\" cannot converge \"behind\" the viewer).  Similarly, the far value must be greater than the near value (as the \"far\" plane of the frustum must be \"farther away\" from the viewer than the near plane).<br/>
<br/>
Works like glFrustum, except it wipes out the current perspective matrix rather than multiplying itself with it.
"
syntax: "frustum(<c>left</c>, <c>right</c>, <c>bottom</c>, <c>top</c>, <c>near</c>, <c>far</c>)"
parameters:
  - label: 'left'
    description: "float: left coordinate of the clipping plane"
  - label: 'right'
    description: "float: right coordinate of the clipping plane"
  - label: 'bottom'
    description: "float: bottom coordinate of the clipping plane"
  - label: 'top'
    description: "float: top coordinate of the clipping plane"
  - label: 'near'
    description: "float: near component of the clipping plane; must be greater than zero"
  - label: 'far'
    description: "float: far component of the clipping plane; must be greater than the near value"
related:
  - camera
  - endCamera
  - perspective
