category: PVector
subcategory: Method
description: "
Returns a new 3D unit vector with a random direction.  If you pass in <b>this</b> as an argument, it will use the PApplet's random number generator.
"
syntax: ".random3D()\n.random3D(<c>parent</c>)\n.random3D(<c>target</c>)\n.random3D(<c>target</c>, <c>parent</c>)"
parameters:
  - label: 'parent'
    description: "PApplet: current PApplet instance"
  - label: 'target'
    description: "PVector: the target vector (if null, a new vector will be created)"
related:
  - PVector_random2D
