category: Input
subcategory: Mouse
description: "
The system variable <b>pmouseY</b> always contains the vertical position of the mouse in the frame previous to the current frame.
<br><br>
For more detail on how <b>pmouseY</b> is updated inside of mouse events and <b>draw()</b>, see the reference for <b>pmouseX</b>.
"
syntax: ""
related:
  - mouseX
  - mouseY
  - pmouseX
  - mousePressed_var
  - mousePressed
  - mouseReleased
  - mouseClicked
  - mouseMoved
  - mouseDragged
  - mouseButton
  - mouseWheel
