category: Input
subcategory: Keyboard
description: "
The Boolean system variable <b>keyPressed</b> is <b>True</b> if any key is pressed and <b>False</b> if no keys are pressed.
"
syntax: ""
related:
  - key
  - keyCode
  - keyPressed_var
  - keyReleased
