category: Math
subcategory: Random
description: "
Generates random numbers. Each time the <b>random()</b> function is called, it returns an unexpected value within the specified range. If only one parameter is passed to the function, it will return a float between zero and the value of the <b>high</b> parameter. For example, <b>random(5)</b> returns values between 0 and 5 (starting at zero, and up to, but not including, 5).<br/>
<br/>
If two parameters are specified, the function will return a float with a value between the two values. For example, <b>random(-5, 10.2)</b> returns values starting at -5 and up to (but not including) 10.2. To convert a floating-point random number to an integer, use the <b>int()</b> function.
"
syntax: "random(<c>high</c>)\nrandom(<c>low</c>, <c>high</c>)"
parameters:
  - label: 'low'
    description: "float: lower limit"
  - label: 'high'
    description: "float: upper limit"
related:
  - randomSeed
  - noise
