category: Math
subcategory: Calculation
description: "
Facilitates exponential expressions. The <b>pow()</b> function is an efficient way of multiplying numbers by themselves (or their reciprocals) in large quantities. For example, <b>pow(3, 5)</b> is equivalent to the expression 3*3*3*3*3 and <b>pow(3, -5)</b> is equivalent to 1 / 3*3*3*3*3.
"
syntax: "ow(<c>n</c>, <c>e</c>"
parameters:
  - label: 'n'
    description: "float: base of the exponential expression"
  - label: 'e'
    description: "float: power by which to raise the base"
related:
  - sqrt
