category: PImage
subcategory: Method
description: "
Updates the image with the data in its <b>pixels</b> list. Use in conjunction with <b>loadPixels()</b>. If you're only reading pixels from the list, there's no need to call <b>updatePixels()</b>.
<br/><br/>
Certain renderers may or may not seem to require <b>loadPixels()</b> or <b>updatePixels()</b>. However, the rule is that any time you want to manipulate the <b>pixels</b> list, you must first call <b>loadPixels()</b>, and after changes have been made, call <b>updatePixels()</b>. Even if the renderer may not seem to use this function in the current Processing release, this will always be subject to change.
<br/> <br/>
Currently, none of the renderers use the additional parameters to <b>updatePixels()</b>, however this may be implemented in the future. 
"
syntax: "updatePixels()\n"
