category: Math
subcategory: Operators
description: "
Combines multiplication with assignment. The expression <b>a *= b</b> is equivalent to <b>a = a * b</b>. 
"
syntax: "<c>value1</c> *= <c>value2</c>"
parameters:
  - label: 'value1'
    description: "int or float"
  - label: 'value2'
    description: "any numerical value the same datatype as value1"
related:
  - assign
  - multiply
