category: Data
subcategory: List Functions
description: "
Returns a sorted copy of the given list (or other iterable). Like the
<b>sort()</b> method of the list object, it can take an optional <b>key</b>
parameter to specify a function that should be evaluated for each item in the
list before sorting that item. The optional parameter <b>reverse</b>, if set
to <b>True</b>, causes <b>sorted()</b> to perform its sorting operation in
reverse order. <br/><br/>

The <b>sorted()</b> function differs from a list object's <b>sort()</b> method
in two important ways. First, it returns a copy of the sorted list, leaving the
original list intact (instead of sorting the list in-place). Second,
<b>sorted()</b> works with any iterable (e.g., strings, tuples, dictionaries),
not just lists.
<br/><br/>

For more information and examples, consult the <a href=\"https://wiki.python.org/moin/HowTo/Sorting/\">Sorting Mini-HOWTO</a> on the <a href=\"https://wiki.python.org/moin/FrontPage\">Python Wiki</a>.
"
syntax: "sorted(<c>iterable</c>)\nsorted(<c>iterable</c>, reverse=True)\nsorted(<c>iterable</c>, key=<c>fn</c>)"
parameters:
  - label: 'list'
    description: "list to sort"
  - label: 'count'
    description: "int: number of elements to sort, starting from 0"
related:
  - list_reverse
