category: Color
subcategory: Creating & Reading
description: "
Extracts the alpha value from a color.
"
syntax: "alpha(rgb)"
parameters:
  - label: 'rgb'
    description: "int: any value of the color datatype"
related:
  - red
  - green
  - blue
  - hue
  - saturation
  - brightness
