category: Structure
subcategory: 
description: "
The <b>except</b> keyword is used with <b>try</b> to handle exceptions. When an
exception is thrown inside a <b>try</b> block, the code inside the
<b>except</b> block with a matching exception class name is run. If an
<b>as</b> clause is given, the exception itself will be available inside this
class as an object with the specified temporary name. Most exception objects
have an attribute <b>message</b>, which can be accessed to further explain the
condition that caused the exception to be raised.
"
syntax: "try:\n  tryStatements\nexcept <c>exception</c> as <c>tmpName</c>:\n  exceptStatements"
parameters:
  - label: 'tryStatements'
    description: "if this code throws an exception, then the code in \"except\" is run"
  - label: 'exception'
    description: "the exception that was thrown"
  - label: 'tmpName'
    description: "a temporary name for the exception (available in exception-handling block)"
  - label: 'exceptStatements'
    description: "code that handles the exception"
related:
  - try
