category: Lights, Camera
subcategory: Material Properties
description: "
Sets the ambient reflectance for shapes drawn to the screen. This is combined with the ambient light component of environment. The color components set through the parameters define the reflectance. For example in the default color mode, setting v1=255, v2=127, v3=0, would cause all the red light to reflect and half of the green light to reflect. Used in combination with <b>emissive()</b>, <b>specular()</b>, and <b>shininess()</b> in setting the material properties of shapes.
"
syntax: "ambient(<c>rgb</c>)\nambient(<c>gray</c>)\nambient(<c>v1</c>, <c>v2</c>, <c>v3</c>)"
parameters:
  - label: 'rgb'
    description: "int: any value of the color datatype"
  - label: 'gray'
    description: "float: number specifying value between white and black"
  - label: 'v1'
    description: "float: red or hue value (depending on current color mode)"
  - label: 'v2'
    description: "float: green or saturation value (depending on current color mode"
  - label: 'v2'
    description: "float: blue or brightness value (depending on current color mode)"
related:
  - emissive
  - specular
  - shininess
