category: Math
subcategory: Random
description: "
Sets the seed value for <b>noise()</b>. By default, <b>noise()</b> produces different results each time the program is run. Set the <b>seed</b> parameter to a constant to return the same pseudo-random numbers each time the software is run. 
"
syntax: "noiseSeed(<c>seed</c>)"
parameters:
  - label: 'seed'
    description: "int: seed value"
related:
  - noise
  - noiseDetail
  - random
  - randomSeed
