category: Transform
subcategory: 
description: "
Multiplies the current matrix by the one specified through the parameters. This is very slow because it will try to calculate the inverse of the transform, so avoid it whenever possible. The equivalent function in OpenGL is glMultMatrix().
"
syntax: "applyMatrix(source)\napplyMatrix(<c>n00</c>, <c>n01</c>, <c>n02</c>, <c>n10</c>, <c>n11</c>, <c>n12</c>)\napplyMatrix(<c>n00</c>, <c>n01</c>, <c>n02</c>, <c>n03</c>, <c>n10</c>, <c>n11</c>, <c>n12</c>, <c>n13</c>, <c>n20</c>, <c>n21</c>, <c>n22</c>, <c>n23</c>, <c>n30</c>, <c>n31</c>, <c>n32</c>, <c>n33</c>)"
parameters:
  - label: 'n00'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n01'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n02'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n10'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n11'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n12'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n03'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n13'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n20'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n21'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n22'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n23'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n30'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n31'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n32'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
  - label: 'n33'
    description: "float: numbers which define the 4x4 matrix to be multiplied"
related:
  - pushMatrix
  - popMatrix
  - resetMatrix
  - printMatrix
