category: Data
subcategory: Composite
description: "
Tuples are one of Python's basic composite data types, along with lists
and dictionaries. A tuple is a lot like a list, in that it consists of a
sequence of elements that can be accessed by index. However, unlike a list,
a tuple can't be modified after it's created. (Tuples can't be assigned to
by index, nor do they have an <b>append()</b> method.)<br/><br/>

You can convert a list to a tuple using the <b>tuple()</b> function, or
convert a tuple to a list using <b>list()</b>.<br/><br/>

Because tuples have a fixed size, Python can make some optimizations behind the
scenes regarding how they're stored in memory. For this reason, tuples can be
marginally faster and more efficient than lists in some applications. Because
tuples are immutable (i.e., they can't be changed after creation), they are
also \"hashable\" and can be used as keys in dictionaries.<br/><br/>

When writing a tuple literal that has only one element, you need to put a
comma after that element. (Otherwise, Python will interpret the parentheses
as \"grouping\" a single expression for the purposes of controlling the order
of execution.)

"
syntax: "	var = (elem1, ..., elemN)"
parameters:
  - label: 'elem'
    description: "any element to store within the tuple"
related:
  - list
  - dictionary
  - indexbrackets
  - parentheses
