category: Shape
subcategory: 2D Primitives
description: "Draws a rectangle to the screen. A rectangle is a four-sided shape with every angle at ninety degrees. By default, the first two parameters set the location of the upper-left corner, the third sets the width, and the fourth sets the height. The way these parameters are interpreted, however, may be changed with the <b>rectMode()</b> function.<br />
<br />
To draw a rounded rectangle, add a fifth parameter, which is used as the radius value for all four corners.<br/>
<br/>
To use a different radius value for each corner, include eight parameters. When using eight parameters, the latter four set the radius of the arc at each corner separately, starting with the top-left corner and moving clockwise around the rectangle."
syntax: "rect(<c>a</c>, <c>b</c>, <c>c</c>, <c>d</c>)\nrect(<c>a</c>, <c>b</c>, <c>c</c>, <c>d</c>, <c>r</c>)\nrect(<c>a</c>, <c>b</c>, <c>c</c>, <c>d</c>, <c>tl</c>, <c>tr</c>, <c>br</c>, <c>bl</c>)"
parameters:
  - label: a
    description: x-coordinate of the rectangle by default
  - label: b
    description: y-coordinate of the rectangle by default
  - label: c
    description: width of the rectangle by default
  - label: d
    description: height of the rectangle by default
  - label: r
    description: radii for all four corners
  - label: tl
    description: radius for top-left corner
  - label: tr
    description: radius for top-right corner
  - label: br
    description: radius for bottom-right corner
  - label: bl
    description: radius for bottom-left corner
related:
  - rectMode
  - quad
