category: Shape
subcategory: Loading & Displaying
description: "
Loads geometry into a variable of type <b>PShape</b>. SVG and OBJ files may be loaded. To load correctly, the file must be located in the data directory of the current sketch. In most cases, <b>loadShape()</b> should be used inside <b>setup()</b> because loading shapes inside <b>draw()</b> will reduce the speed of a sketch.<br />
<br />
Alternatively, the file maybe be loaded from anywhere on the local computer using an absolute path (something that starts with / on Unix and Linux, or a drive letter on Windows), or the filename parameter can be a URL for a file found on a network.<br />
<br />
If the file is not available or an error occurs, <b>null</b> will be returned and an error message will be printed to the console. The error message does not halt the program, however the null value may cause a NullPointerException if your code does not check whether the value returned is null.<br/>
"
syntax: "loadShape(<c>filename</c>)\nloadShape(<c>filename</c>, <c>options</c>)"
parameters:
  - label: 'filename'
    description: "String: name of file to load, can be .svg or .obj"
related:
  - PShape
  - createShape
