category: Image
subcategory: Textures
description: "
Defines if textures repeat or draw once within a texture map. The two parameters are CLAMP (the default behavior) and REPEAT. This function only works with the P2D and P3D renderers.
"
syntax: "	textureWrap(mode)"
parameters:
  - label: 'mode'
    description: "int: either CLAMP or REPEAT"
related:
  - texture
  - textureMode
