category: XMLElement
subcategory: Method
description: "
Removes the specified element.  First use <b>getChild()</b> to get a reference to the desired element.  Then pass that reference to <b>removeChild()</b> to delete it.
"
syntax: ".removeChild(kid)\n"
