category: Input
subcategory: Mouse
description: "
The <b>mousePressedVar</b> variable stores whether or not a mouse button is currently being pressed. The value is true when any mouse button is pressed, and false if no button is pressed. The <b>mouseButton</b> variable (see the related reference entry) can be used to determine which button has been pressed.
"
related:
  - mouseX
  - mouseY
  - pmouseX
  - pmouseY
  - mousePressed
  - mouseReleased
  - mouseClicked
  - mouseMoved
  - mouseDragged
  - mouseButtonVar
  - mouseWheel
