category: Control
subcategory: Logical Operators
description: "
<p>Compares two expressions and returns <b>True</b> if one or both evaluate to <b>True</b>. Returns <b>False</b> only if both expressions are <b>False</b>. The following list shows all possible combinations:
<pre>
True or False   # Evaluates True because the first is True
False or True   # Evaluates True because the second is True
True or True    # Evaluates True because both are True
False or False  # Evaluates False because both are False
</pre>
<p>The \"or\" operator is <i>short-circuiting</i>; it will not bother to evaluate its
second expression of the first is True. That means, in the following example, that
<tt>DoSomething</tt> is never called:
<pre>
def DoSomething():
    print \"You will never see this message!\"
    return True

x = True
if x or DoSomething():
    print \"This always happens.\"
</pre>

"
syntax: "<c>expression1</c> or <c>expression2</c>"
parameters:
  - label: 'expression1'
    description: "any valid expression"
  - label: 'expression2'
    description: "any valid expression"
related:
  - logicalAND
  - logicalNOT
  - if
