category: Data
subcategory: String Methods
description: "
Returns a copy of the string with all occurrences of an old substring replaced by a new substring.
"
syntax: "s.replace(<c>old</c>, <c>new</c>)"
parameters:
  - label: 'old'
    description: "substring to replace"
  - label: 'new'
    description: "substring to substitute old with"
related:
  - string_split
  - string_join
  - string_strip
  - string_find
  - string_formatting
