category: Shape
subcategory: Vertex
description: "
Specifies vertex coordinates for Bezier curves. Each call to <b>bezierVertex()</b> defines the position of two control points and one anchor point of a Bezier curve, adding a new segment to a line or shape. The first time <b>bezierVertex()</b> is used within a <b>beginShape()</b> call, it must be prefaced with a call to <b>vertex()</b> to set the first anchor point. This function must be used between <b>beginShape()</b> and <b>endShape()</b> and only when there is no MODE parameter specified to <b>beginShape()</b>. Using the 3D version requires rendering with P3D (see the Environment reference for more information).
"
syntax: "bezierVertex(<c>x2</c>, <c>y2</c>, <c>x3</c>, <c>y3</c>, <c>x4</c>, <c>y4</c>)\nbezierVertex(<c>x2</c>, <c>y2</c>, <c>z2</c>, <c>x3</c>, <c>y3</c>, <c>z3</c>, <c>x4</c>, <c>y4</c>, <c>z4</c>)"
parameters:
  - label: 'x2'
    description: "float: the x-coordinate of the 1st control point"
  - label: 'y2'
    description: "float: the y-coordinate of the 1st control point"
  - label: 'z2'
    description: "float: the z-coordinate of the 1st control point"
  - label: 'x3'
    description: "float: the x-coordinate of the 2nd control point"
  - label: 'y3'
    description: "float: the y-coordinate of the 2nd control point"
  - label: 'z3'
    description: "float: the z-coordinate of the 2nd control point"
  - label: 'x4'
    description: "float: the x-coordinate of the anchor point"
  - label: 'y4'
    description: "float: the y-coordinate of the anchor point"
  - label: 'z4'
    description: "float: the z-coordinate of the anchor point"
related:
  - curveVertex
  - vertex
  - quadraticVertex
  - bezier
