category: PShape
subcategory: Method
description: "
Increases or decreases the size of a shape by expanding and contracting vertices. Shapes always scale from the relative origin of their bounding box. Scale values are specified as decimal percentages. For example, the method call <b>scale(2.0)</b> increases the dimension of a shape by 200%. Subsequent calls to the method multiply the effect. For example, calling <b>scale(2.0)</b> and then <b>scale(1.5)</b> is the same as <b>scale(3.0)</b>. This transformation is applied directly to the shape; it's not refreshed each time <b>draw()</b> is run. 
<br /><br />
Using this method with the <b>z</b> parameter requires using the P3D parameter in combination with size. 
"
syntax: "<c>sh</c>.scale(<c>s</c>)\n<c>sh</c>.scale(<c>x</c>, <c>y</c>)\n<c>sh</c>.scale(<c>x</c>, <c>y</c>, <c>z</c>)"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
  - label: 's'
    description: "float: percentate to scale the object"
  - label: 'x'
    description: "float: percentage to scale the object in the x-axis"
  - label: 'y'
    description: "float: percentage to scale the object in the y-axis"
  - label: 'z'
    description: "ifloat: percentage to scale the object in the z-axis"
related:
  - rotate
  - translate
  - resetMatrix
