category: Table
subcategory: Method
description: "
Gets all rows from the table.  Returns an iterator, so <b>for</b> must be used to iterate through all the rows, as shown in the example above.
"
syntax: ".rows()"
related:
  - Table_getRow
  - Table_findRow
  - Table_findRows
  - Table_matchRow
  - Table_matchRows
