category: Table
subcategory: Method
description: "
Trims leading and trailing whitespace, such as spaces and tabs, from string table values. If no column is specified, then the values in all columns and rows are trimmed. A specific column may be referenced by either its ID or title.
"
syntax: ".trim()\n.trim(<c>column</c>)\n.trim(<c>columnName</c>)"
parameters:
  - label: 'column'
    description: "int: ID number of the column to trim"
  - label: 'columnName'
    description: "String: title of the column to trim"
related:
  - Table_removeTokens
