category: Environment
subcategory: 
description: "
Defines the dimension of the display window in units of pixels. The <b>size()</b> function must be the first line of code, or the first code inside <b>setup()</b>. Any code that appears before the <b>size()</b> command may run more than once, which can lead to confusing results.<br/>
<br/>
The system variables <b>width</b> and <b>height</b> are set by the parameters passed to this function. If <b>size()</b> is not used, the window will be given a default size of 100x100 pixels. <br/>
<br/>
The <b>size()</b> function can only be used once inside a sketch, and it cannot be used for resizing.<br/>
<br/>
Do not use variables as the parameters to <b>size()</b> function, because it will cause problems when exporting your sketch. When variables are used, the dimensions of your sketch cannot be determined during export. Instead, employ numeric values in the <b>size()</b> statement, and then use the built-in <b>width</b> and <b>height</b> variables inside your program when the dimensions of the display window are needed.<br/>
<br/>
The maximum width and height is limited by your operating system, and is usually the width and height of your actual screen. On some machines it may simply be the number of pixels on your current screen, meaning that a screen of 800x600 could support <b>size(1600, 300)</b>, since that is the same number of pixels. This varies widely, so you'll have to try different rendering modes and sizes until you get what you're looking for. If you need something larger, use <b>createGraphics</b> to create a non-visible drawing surface.<br/>
<br/>
The <b>renderer</b> parameter selects which rendering engine to use. For example, if you will be drawing 3D shapes, use <b>P3D</b>. In addition to the default renderer, other renderers are:<br/>
<br/>
<b>P2D</b> (Processing 2D): A renderer that supports two-dimensional drawing.<br/>
<br/>
<b>P3D</b> (Processing 3D): 3D graphics renderer that makes use of OpenGL-compatible graphics hardware.<br/>
<br/>
<b>PDF</b>: The PDF renderer draws 2D graphics directly to an Acrobat PDF file. This produces excellent results when you need vector shapes for high-resolution output or printing. You must first use Import Library &rarr; PDF to make use of the library. More information can be found in the PDF library reference.<br/>
<br/>
"
syntax: "size(<c>w</c>,<c>h</c>)\nsize(<c>w</c>,<c>h</c>,<c>renderer</c>)"
parameters:
  - label: 'w'
    description: "int: width of the display window in units of pixels"
  - label: 'h'
    description: "int: height of the display window in units of pixels"
  - label: 'renderer'
    description: "String: Either P2D, P3D, or PDF"
related:
  - width
  - PShape_height
