category: Image
subcategory: Loading & Displaying
description: "
Modifies the location from which images are drawn by changing the way in which parameters given to <b>image()</b> are intepreted.<br/>
<br/>
The default mode is <b>imageMode(CORNER)</b>, which interprets the second and third parameters of <b>image()</b> as the upper-left corner of the image. If two additional parameters are specified, they are used to set the image's width and height.<br/>
<br/>
<b>imageMode(CORNERS)</b> interprets the second and third parameters of <b>image()</b> as the  location of one corner, and the fourth and fifth parameters as the opposite corner.<br/>
<br/>
<b>imageMode(CENTER)</b> interprets the second and third parameters of <b>image()</b> as the image's center point. If two additional parameters are specified, they are used to set the image's width and height.<br/>
<br/>
The parameter must be written in ALL CAPS because Processing is a case-sensitive language.
"
syntax: "mageMode(mode"
parameters:
  - label: 'mode'
    description: "int: either CORNER, CORNERS, or CENTER"
related:
  - loadImage
  - PImage
  - image
  - background
