category: Math
subcategory: Bitwise Operators
description: "
Compares each corresponding bit in the binary representation of the values. For each comparison two 1's yield 1, 1 and 0 yield 0, and two 0's yield 0. This is easy to see when we look at the binary representation of numbers<br/>
<br/>
<pre>  11010110  # 214
& 01011100  # 92
  --------
  01010100  # 84</pre>
<br/>
To see the binary representation of a number, use the <b>binary()</b> function with <b>print()</b>.
"
syntax: "c>value</c> &amp; <c>value2</c></s"
parameters:
  - label: 'value1'
    description: "int, char, byte"
  - label: 'value2'
    description: "int, char, byte"
related:
  - bitwiseOR
  - binary
