category: Structure
subcategory: 
description: "
Keyword used to indicate the value to return from a function.
<br/>
The keyword <b>return</b> may also be used to break out of a function, thus not allowing the program to the remaining statements. (See the third example above.)
"
syntax: "def <c>function</c>:\n    <c>statements</c>\n    return <c>value</c>"
parameters:
  - label: 'function'
    description: "the function being defined"
  - label: 'statements'
    description: "any valid statements"
  - label: 'value'
    description: "the value to return"
