category: Lights, Camera
subcategory: Lights
description: "
Adds a directional light. Directional light comes from one direction: it is stronger when hitting a surface squarely, and weaker if it hits at a gentle angle. After hitting a surface, directional light scatters in all directions. Lights need to be included in the <b>draw()</b> to remain persistent in a looping program. Placing them in the <b>setup()</b> of a looping program will cause them to only have an effect the first time through the loop. The <b>v1</b>, <b>v2</b>, and <b>v3</b> parameters are interpreted as either RGB or HSB values, depending on the current color mode. The <b>nx</b>, <b>ny</b>, and <b>nz</b> parameters specify the direction the light is facing. For example, setting <b>ny</b> to -1 will cause the geometry to be lit from below (since the light would be facing directly upward).
"
syntax: "directionalLight(<c>v1</c>, <c>v2</c>, <c>v3</c>, <c>nx</c>, <c>ny</c>, <c>nz</c>)"
parameters:
  - label: 'v1'
    description: "float: red or hue value (depending on current color mode)"
  - label: 'v2'
    description: "float: green or saturation value (depending on current color mode)"
  - label: 'v3'
    description: "float: blue or brightness value (depending on current color mode)"
  - label: 'nx'
    description: "float: direction along the x-axis"
  - label: 'ny'
    description: "float: direction along the y-axis"
  - label: 'nz'
    description: "float: direction along the z-axis"
related:
  - lights
  - ambientLight
  - pointLight
  - spotLight
