category: Math
subcategory: Trigonometry
description: "
Calculates the angle (in radians) from a specified point to the coordinate origin as measured from the positive x-axis. Values are returned as a <b>float</b> in the range from <b>PI</b> to <b>-PI</b>. The <b>atan2()</b> function is most often used for orienting geometry to the position of the cursor.  Note: The y-coordinate of the point is the first parameter, and the x-coordinate is the second parameter, due the the structure of calculating the tangent.
"
syntax: "atan2(<c>y</c>, <c>x</c>)"
parameters:
  - label: 'y'
    description: "float: y-coordinate of the point"
  - label: 'x'
    description: "float: x-coordinate of the point"
related:
  - tan
