category: Data
subcategory: Conversion
description: "

Takes an \"iterable\" object as a parameter and returns a list of items in the
object. (An \"iterable\" object is an object that can be looped over, such as a
list, string, dictionary, set or tuple; <a href=\"https://docs.python.org/2/glossary.html#term-iterable\">more information here</a>.) This function is useful
for converting a string to list of individual characters, for making copies
of existing lists, and for making empty lists.<br/><br/>

This function is also useful for converting Python iterators (returned from,
e.g., <b>reversed()</b> or the dictionary object's <b>iteritems()</b>) and
converting them to lists.

"
syntax: "list(<c>x</c>)"
parameters:
  - label: 'x'
    description: "iterable to convert to a list"
