category: PShape
subcategory: Method
description: "
This method is used to complete a custom shape created with the <b>createShape()</b> function. It's always and only used with <b>createShape()</b>. 
"
syntax: "<c>sh</c>.endShape()\n<c>sh</c>.endShape(mode)"
parameters:
  - label: 'sh'
    description: "PShape: any variable of type PShape"
related:
  - PShape_beginShape
