category: Color
subcategory: Setting
description: "
Changes the way Processing interprets color data. By default, the parameters for <b>fill()</b>, <b>stroke()</b>, <b>background()</b>, and <b>color()</b> are defined by values between 0 and 255 using the RGB color model. The <b>colorMode()</b> function is used to change the numerical range used for specifying colors and to switch color systems. For example, calling <b>colorMode(RGB, 1.0)</b> will specify that values are specified between 0 and 1. The limits for defining colors are altered by setting the parameters <b>max</b>, <b>max1</b>, <b>max2</b>, <b>max3</b>, and <b>maxA</b>. 
"
syntax: "colorMode(<c>mode</c>)\ncolorMode(<c>mode</c>, <c>max</c>)\ncolorMode(<c>mode</c>, <c>max1</c>, <c>max2</c>, <c>max3</c>)\ncolorMode(<c>mode</c>, <c>max1</c>, <c>max2</c>, <c>max3</c>, <c>maxA</c>)"
parameters:
  - label: 'mode'
    description: "int: Either RGB or HSB, corresponding to Red/Green/Blue and Hue/Saturation/Brightness"
  - label: 'max'
    description: "float: range for the red or hue depending on the current color mode"
  - label: 'max1'
    description: "float: range for the red or hue depending on the current color mode"
  - label: 'max2'
    description: "float: range for the green or saturation depending on the current color mode"
  - label: 'max3'
    description: "float: range for the blue or brightness depending on the current color mode"
  - label: 'maxA'
    description: "float: range for the alpha"
related:
  - background
  - fill
  - stroke
