category: Shape
subcategory: Curves
description: "
Sets the resolution at which curves display. The default value is 20. This function is only useful when using the P3D renderer as the default P2D renderer does not use this information.
"
syntax: "curveDetail(<c>detail</c>)"
parameters:
  - label: 'detail'
    description: "int: resolution of the curves"
related:
  - curve
  - curveVertex
  - curveTightness
