category: PImage
subcategory: Method
description: "
Filters the image as defined by one of the following modes:<br />
<br />
THRESHOLD<br />
Converts the image to black and white pixels depending if they are above or below the threshold defined by the level parameter. The parameter must be between 0.0 (black) and 1.0 (white). If no level is specified, 0.5 is used.<br />
<br />
GRAY<br />
Converts any colors in the image to grayscale equivalents. No parameter is used.<br />
<br />
OPAQUE<br />
Sets the alpha channel to entirely opaque. No parameter is used.<br />
<br />
INVERT<br />
Sets each pixel to its inverse value. No parameter is used.<br />
<br />
POSTERIZE<br />
Limits each channel of the image to the number of colors specified as the parameter. The parameter can be set to values between 2 and 255, but results are most noticeable in the lower ranges.<br />
<br />
BLUR<br />
Executes a Guassian blur with the level parameter specifying the extent of the blurring. If no parameter is used, the blur is equivalent to Guassian blur of radius 1. Larger values increase the blur.<br />
<br />
ERODE<br />
Reduces the light areas. No parameter is used.<br />
<br />
DILATE<br />
Increases the light areas. No parameter is used.
"
syntax: "<c>pimg</c>.<c>filter</c>(<c>kind</c>)\n<c>pimg</c>.<c>filter</c>(<c>kind</c>, <c>param</c>)"
parameters:
  - label: 'pimg'
    description: "PImage: any object of type PImage"
  - label: 'kind'
    description: "int: Either THRESHOLD, GRAY, OPAQUE, INVERT, POSTERIZE, BLUR, ERODE, or DILATE"
  - label: 'param'
    description: "float: unique for each, see above"
