category: Image
subcategory: Pixels
description: "
Copies a region of pixels from the display window to another area of the display window and copies a region of pixels from an image used as the <b>srcImg</b> parameter into the display window. If the source and destination regions aren't the same size, it will automatically resize the source pixels to fit the specified target region. No alpha information is used in the process, however if the source image has an alpha channel set, it will be copied as well.
<br /><br />
As of release 0149, this function ignores <b>imageMode()</b>.
"
syntax: "copy(<c>sx</c>, <c>sy</c>, <c>sw</c>, <c>sh</c>, <c>dx</c>, <c>dy</c>, <c>dw</c>, <c>dh</c>)\ncopy(<c>src</c>, <c>sx</c>, <c>sy</c>, <c>sw</c>, <c>sh</c>, <c>dx</c>, <c>dy</c>, <c>dw</c>, <c>dh</c>)"
parameters:
  - label: 'sx'
    description: "int: X coordinate of the source's upper left corner"
  - label: 'sy'
    description: "int: Y coordinate of the source's upper left corner"
  - label: 'sw'
    description: "int: source image width"
  - label: 'sh'
    description: "int: source image height"
  - label: 'dx'
    description: "int: X coordinate of the destination's upper left corner"
  - label: 'dy'
    description: "int: Y coordinate of the destination's upper left corner"
  - label: 'dw'
    description: "int: destination image width"
  - label: 'dh'
    description: "int: destination image height"
  - label: 'src'
    description: "PImage: an image variable referring to the source image."
related:
  - alpha
  - PImage_blend
