category: Math
subcategory: Calculation
description: "
Determines the largest value in a sequence of numbers, and then returns that value. <b>max()</b> accepts either two or three <b>float</b> or <b>int</b> values as parameters, or an array of any length.
"
syntax: "\nmax(<c>a</c>, <c>b</c>)\nmax(<c>a</c>, <c>b</c>, <c>c</c>)\nmax(<c>list</c>)"
parameters:
  - label: 'a'
    description: "float, or int: first number to compare"
  - label: 'b'
    description: "float, or int: second number to compare"
  - label: 'c'
    description: "float, or int: third number to compare"
  - label: 'list'
    description: "float, or int: list of numbers to compare"
related:
  - min
