category: Control
subcategory: Conditionals
description: "
A shortcut for writing an <b>if</b> and <b>else</b> structure. Conditional expressions in Python take the form <b>expression1 if test else expression2</b>. If the <b>test</b> evaluates to <b>True</b>, <b>expression1</b> is evaluated and returned. If the <b>condition</b> evaluates to <b>False</b>, <b>expression2</b> is evaluated and returned.
<br /><br />
The following conditional expression: <br />
<pre>result = expression1 if test else expression2</pre><br />
is equivalent to this structure: <br />
<pre>if test:<br />
  result = expression1 <br />
 else: <br />
  result = expression2 <br />
</pre>
"
syntax: "<c>expression1</c> if <c>test</c> else <c>expression2</c>"
parameters:
  - label: 'test'
    description: "any valid expression which evaluates to True or False"
  - label: 'expression1'
    description: "any valid expression"
  - label: 'expression2'
    description: "any valid expression"
related:
  - if
  - else
